### ISSUE TITLE
Vertical scrolling pinned column Issue

### ISSUE THREAD

**Issue by lmb32854** [ag-grid/ag-grid#2140]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
Hi,

I'm using AG-GRID in my Angular4 App, and today I tried it on Microsoft Edge and I noticed that if you have a column pinned and you scroll vertically, the pinned column does not scroll at the same time that the rest of the columns. It makes the page look really "laggy".

I get to the "Column Pinning" section of the [official website](https://www.ag-grid.com/javascript-grid-pinning/#gsc.tab=0) with a Microsoft Edge and on this page the grid works fine.

I tried to make a fresh project, I copied all the code from the above link and, it's again laggy.

**Expected behavior**
The pinned column scroll as the others columns

**Minimal reproduction of the problem with instructions**
Make a new Angular4/cli project
`ng new PinnedIssue`
`cd PinnedIssue`
`npm i ag-grid --save`
`npm i ag-grid-angular --save`

Then copy all the code from the first exemple of the Column Pinning page :

AppComponent.ts
```
public gridApi;
  public gridColumnApi;

  public columnDefs;

  constructor(private http: HttpClient) {
    this.columnDefs = [
      {
        headerName: "#",
        colId: "rowNum",
        valueGetter: "node.id",
        width: 40,
        pinned: "left"
      },
      {
        headerName: "Athlete",
        field: "athlete",
        width: 150,
        pinned: "left"
      },
      {
        headerName: "Age",
        field: "age",
        width: 90,
        pinned: "left"
      },
      {
        headerName: "Country",
        field: "country",
        width: 120
      },
      {
        headerName: "Year",
        field: "year",
        width: 90
      },
      {
        headerName: "Date",
        field: "date",
        width: 110
      },
      {
        headerName: "Sport",
        field: "sport",
        width: 110
      },
      {
        headerName: "Gold",
        field: "gold",
        width: 100
      },
      {
        headerName: "Silver",
        field: "silver",
        width: 100
      },
      {
        headerName: "Bronze",
        field: "bronze",
        width: 100
      },
      {
        headerName: "Total",
        field: "total",
        width: 100,
        pinned: "right"
      }
    ];
  }

  clearPinned() {
    this.gridColumnApi.setColumnPinned("rowNum", null);
    this.gridColumnApi.setColumnPinned("athlete", null);
    this.gridColumnApi.setColumnPinned("age", null);
    this.gridColumnApi.setColumnPinned("country", null);
    this.gridColumnApi.setColumnPinned("total", null);
  }

  resetPinned() {
    this.gridColumnApi.setColumnPinned("rowNum", "left");
    this.gridColumnApi.setColumnPinned("athlete", "left");
    this.gridColumnApi.setColumnPinned("age", "left");
    this.gridColumnApi.setColumnPinned("country", null);
    this.gridColumnApi.setColumnPinned("total", "right");
  }

  pinCountry() {
    this.gridColumnApi.setColumnPinned("rowNum", null);
    this.gridColumnApi.setColumnPinned("athlete", null);
    this.gridColumnApi.setColumnPinned("age", null);
    this.gridColumnApi.setColumnPinned("country", "left");
    this.gridColumnApi.setColumnPinned("total", null);
  }

  jumpToCol() {
    var value = (<any>document.getElementById("col")).value;
    if (typeof value !== "string" || value === "") {
      return;
    }
    var index = Number(value);
    if (typeof index !== "number" || isNaN(index)) {
      return;
    }
    var allColumns = this.gridColumnApi.getAllColumns();
    var column = allColumns[index];
    if (column) {
      this.gridApi.ensureColumnVisible(column);
    }
  }

  jumpToRow() {
    var value = (<any>document.getElementById("row")).value;
    var index = Number(value);
    if (typeof index === "number" && !isNaN(index)) {
      this.gridApi.ensureIndexVisible(index);
    }
  }

  onGridReady(params) {
    this.gridApi = params.api;
    this.gridColumnApi = params.columnApi;

    this.http
      .get("https://raw.githubusercontent.com/ag-grid/ag-grid-docs/master/src/olympicWinnersSmall.json")
      .subscribe(data => {
        params.api.setRowData(data);
      });
  }
```

AppComponent.html
```
<div style="height: 500px; padding-top: 60px; box-sizing: border-box;">
    <ag-grid-angular
    #agGrid
    style="width: 500px; height: 100%;"
    id="myGrid"
    class="ag-theme-fresh"
    [columnDefs]="columnDefs"
    [enableColResize]="true"
    (gridReady)="onGridReady($event)"
    ></ag-grid-angular>
</div>
<div style="position: absolute; top: 0px; left: 0px;">
    <div style="padding: 4px;">
        <button (click)="clearPinned()">Clear Pinned</button>
        <button (click)="resetPinned()">Left = #, Athlete, Age; Right = Total</button>
        <button (click)="pinCountry()">Left = Country</button>
    </div>

    <div style="padding: 4px;">
        Jump to:
        <input placeholder="row" type="text" style="width: 40px" id="row" (input)="jumpToRow()">
        <input placeholder="col" type="text" style="width: 40px" id="col" (input)="jumpToCol()">
    </div>
</div>
```

.angular-cli.json
```
...
"styles": [
        "styles.css",
        "../node_modules/ag-grid/dist/styles/ag-grid.css",
        "../node_modules/ag-grid/dist/styles/ag-theme-fresh.css"
      ],
...
```

app.module.ts

```
import { HttpClientModule } from '@angular/common/http';
import { FormsModule } from '@angular/forms';
import { AgGridModule } from 'ag-grid-angular/main';
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent,
  ],
  imports: [
    BrowserModule,
    FormsModule, // <-- import the FormsModule before binding with [(ngModel)]
    HttpClientModule,
    AgGridModule.withComponents([])
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**Please tell us about your environment:**
I'm on windows, using visual studio code.
My angular cli version is : 1.4.3.

* **ag-Grid version:** X.X.X
ag-grid version : 15.0.0
ag-grid-angular : 15.0.0

* **Browser:**
Microsoft Edge

**Comment by sinsunsan** [comment]
I think you should create a plunkr so that we can test your issue 
Also I feel like your laggy effect is not specific to pinned column. I have the same problem on my app and also experienced it in the plunkr shared in this comment https://github.com/ag-grid/ag-grid/issues/1957#issuecomment-356304659

on Edge, Internet explorer 11 Mozilla  but not Chrome. 
I suppose that the problem is due to a bug in change detection of the library it self. 

can you test @lmb32854 this plunkr in edge and scroll horizontally https://plnkr.co/edit/lPsS36mDQG22dWDH1lKJ?p=info is it the same laggy effect ?

**Comment by lmb32854** [comment]
Hi, 

It's exactly the same effect.

Also to test my issue, you can simply add "pinned: true" in your country column definition and scroll vertically.

**Comment by sinsunsan** [comment]
For me it is probably a performance issue to change detection. 
In those 2 issues #1957 and #2034 they talk about change detection, js profiling... and they suggest disabling change detection in zone... a lot of hack though. 

The fact that there is a lag means that the browser take time to update the rendering as if it were stuck momentarily in a js process. 
Also the fact that firefox is impacted along with IE and edge seems to exclude an internet only problem.

**Comment by aamitsharma2705** [comment]
Hi,

We are facing a similar issue, only in IE. In our scenario we are using aggrid with react to represent grouped data with autogroupcolumn as pinned column. 

Its working in crome and firefox as expected but for IE when we scroll there is complete blank screen on right(unpinned) side and left side remained stuck. 

When we try to scroll slowly then its visible that pinned panel is following the body panel that too very slow.

Can you please suggest some solution  for this.

**Comment by avurhd** [comment]
We are facing a similar issue where the pinned and unpinned columns get disconnected while scrolling. Pinned column scrolls first and the unpinned column lags to follow along.

Can you please provide a solution

**Comment by sumcoding** [comment]
My team is also facing this problem, but our primary browser with the issue is Safari. The latest update (18.1.2 at the time of this comment) has made the lag far more apparent as well.

**Comment by bmg-will** [comment]
I am also experiencing this issue as an enterprise user. 

It is probably worth mentioning that this was not an issue for us in version 17.

Ever since upgrading to 18 it feels incredibly buggy when you scroll, we have columns pinned by default making the issue even more noticeable by users.

**Comment by KrisWyb** [comment]
Facing the same issue after upgrade to version 19.0.0
Both in IE11 and Chrome Version 69.0.3497.100

Also,there is a style issue in IE 11,has a blank no use cloumn between pinned column and left columns:
![image](https://user-images.githubusercontent.com/4710590/46456721-6670b980-c7e2-11e8-8672-920e00424a3a.png)

**Comment by makinggoodsoftware** [comment]
Hi

Just to let you know that ag-grid staff is now going to monitor this thread to help find an answer to this issue (hence the ag-grid engaged label)

Thanks for all the feedback

**Comment by makinggoodsoftware** [comment]
Hi,

ag-grid staff does not provide support through github. If you are a customer please contact us through our official support channel. Note that this issue has been flagged as managed-by-the-community, we also recommend you to check stackoverflow, note that if there is no activity on this issue after a while we will close it.

However I am pasting here for you the contents of an article that we have in our knowledge base (that at the moment is only accessible for customers), hope this helps

______________
Getting the scroll to work in ag-grid smoothly across all browsers no matter how many rows and columns is very challenging

We are aware that on occasions is not is as smooth as it should be, in some cases is because we can't make it any faster for a particular browser

https://ag-grid.zendesk.com/hc/en-us/articles/360016128031-The-performance-in-IE-11-is-not-as-good-as-in-Chrome-why-

In any case, we are quite happy with how it works right now, however, we always keep an eye to improve the performance.

We do have tickets that we keep open and that we use as a placeholder so you can see if there are any more improvements coming up.

You will be able to do so in our pipeline (It will be in the 'Next Release' tab if we are planning further improvements)

Performance improvements	AG-1211	IE 11 Performance improvements
Performance improvements	AG-1274	Have no lag with vertical scroll	BACKLOG
Performance improvements	AG-939	Improve horizontal and vertical scrolling in other browsers	BACKLOG
https://www.ag-grid.com/ag-grid-pipeline/

 

In any case, we recommend you to always try to update to the latest version of ag-grid so you can get all the performance improvements



Thanks

**Comment by makinggoodsoftware** [comment]
@sumcoding That issue you reported should have been fixed in v19

AG-1890 |   | 19.0.0 | Pinn + Scroll to bottom on pinned area. Causes slight misalignment of rows
-- | -- | -- | --

**Comment by bmg-will** [comment]
@makinggoodsoftware I can confirm V19 has fixed all manifestations of the issue for us.

**Comment by makinggoodsoftware** [comment]
Closing this as we assume this is not an issue anymore

**Comment by satyendrasinghpanwar** [comment]
This is still an issue in IE Edge and IE 11. I am using ag-grid version 19

**Comment by icreatedanaccount** [comment]
This is still an issue on Chrome 62 on ag-grid enterprise version 21.0.1.

**Comment by MalvikaSingh2409** [comment]
> I am also experiencing this issue as an enterprise user.
> 
> It is probably worth mentioning that this was not an issue for us in version 17.
> 
> Ever since upgrading to 18 it feels incredibly buggy when you scroll, we have columns pinned by default making the issue even more noticeable by users.

It is an issue for us in version 17 as well.

**Comment by gportela85** [comment]
All of the issues that caused pinned containers to be out of sync were fixed in version 21.0.0.
@icreatedanaccount If you are still experiencing any problems with scroll performance, it might be a different issue. Notice that in v24 the capability to debounce the scroll was added, see: https://www.ag-grid.com/javascript-grid-performance/#9-debounce-vertical-scroll
