### ISSUE TITLE
ag-grid-angular peer dependency warnings

### ISSUE THREAD

**Issue by jpike88** [ag-grid/ag-grid#3156]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
```
```
npm WARN ag-grid-angular@21.0.0 requires a peer of @angular/compiler-cli@>=2.1.x but none is installed. You must install peer dependencies yourself.
npm WARN ag-grid-angular@21.0.0 requires a peer of core-js@^2.4.1 but none is installed. You must install peer dependencies yourself.
```

These two libraries should not be peer dependencies, I have neither installed and don't want to install them. The CLI is a development tool, and core-js contains polyfills that should be up to the developers discretion to use if they want to target older browsers. Please remove both completley so the warnings stop

Thanks

**Comment by jpike88** [comment]
@makinggoodsoftware would prefer if this one is actually actioned, marking an issue as 'managed-by-community' would be a frustrating way to address this issue

**Comment by jpike88** [comment]
@seanlandsman would prefer if this one is actually actioned, marking this as 'managed-by-community' would be a frustrating way to address this issue. Those dependency warnings are looking at ancient versions of angular.

**Comment by makinggoodsoftware** [comment]
Hi

Just to let you know that ag-grid staff is now going to monitor this thread to help find an answer to this issue (hence the ag-grid engaged label)

Thanks for all the feedback

**Comment by jpike88** [comment]
@makinggoodsoftware I updated my issue and removed my PR as it was out of date

**Comment by seanlandsman** [comment]
this has been fixed and will be available in our next release

**Comment by jpike88** [comment]
@seanlandsman the fix didn't correctly address my issue. And that's partially my fault.

```ag-grid-angular@21.0.1 requires a peer of core-js@>=2.4.1 but none is installed```

https://github.com/ag-grid/ag-grid/blob/47b7e31fedc525d33abfe37aa197e65f35b86d87/packages/ag-grid-angular/package.json#L64

I'm still getting this error. As I specified initially, some developers may prefer not to use core-js _at all_, as it's just a polyfill library and there are alternative routes. Angular itself doesn't have core-js as a peer dependency (for good reason), so neither should ag-grid-angular.

I've submitted a PR to clearly show what should be done, and that's removing core-js as a peer dependency altogether. I incorrectly relaxed its versioning when it should have been removed.

Please can this issue be reopened thanks

**Comment by MicMicMon** [comment]
Is it planned?

**Comment by NikitaIT** [comment]
@MicMicMon track it https://github.com/ag-grid/ag-grid/pull/3189
