### ISSUE TITLE
reactNext - React Component '...' not created within 1000ms**

### ISSUE THREAD

**Issue by alkorr37** [ag-grid/ag-grid#3222]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/EcryNGfNAWqKd5X2Yzvo?p=preview

**Current behavior**
After quick grid mount/unmount (reactNext) with custom renderers errors like '**React Component '...' not created within 1000ms**' are occured

* **ag-Grid version:** 21.0.1
* **ag-grid-react version:** 21.0.1

**Comment by alkorr37** [comment]
#3222

**Comment by seanlandsman** [comment]
Thanks for reporting this, as well as the PR

**Comment by davis4acca** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by dadamssg** [comment]
Any progress on this? Experiencing the same.

**Comment by seanlandsman** [comment]
This will be fixed in our next release, due next week

**Comment by davis4acca** [comment]
Thank you for your email. This is in our backlog now and we are tracking it with the following reference and description.

AG-3112 -  fast mount/unmount with reactNext throws error

You can follow the status of feature requests, bugs and releases using our pipeline: 

https://www.ag-grid.com/ag-grid-pipeline/

**Comment by mechiland** [comment]
Does this issue really fixed? I upgraded to `21.1.0` got no luck. Still plenty of errors saying "ag-Grid: React Component ... not created within 1000ms"

**Comment by alkorr37** [comment]
problem still persist

**Comment by ten-alk** [comment]
The issue is still reproducible.

**Comment by seanlandsman** [comment]
Do you have an example we can look at?

**Comment by Jacob-Allen** [comment]
This is happening and is reproducible for me as well. In my case its happening when a date column is used. I am using a cell renderer that passes the value through moment and formats it, however, once this error occurs the entire column just shows blank values.

**Comment by galenlong** [comment]
I've found that this happens when the React component cell renderer returns a [fragment](https://reactjs.org/docs/fragments.html#short-syntax) instead of an element. Changing my component to return a div fixed this problem, but I was able to render fragments before I set reactNext to true.

**Comment by seanlandsman** [comment]
@ten-alk @Jacob-Allen can you provide reproducible examples of the problem? plunker, github repo etc? 

I'll prioritise fixing this for the next release

@galenlong thanks, I'll make a note of this test case along with any others raised

**Comment by dcjones1** [comment]
I have the same issue in a custom header renderer. When the columns are reordered, I have to have the grid unmount/mount again and my headers lose all content and remains blank.

**Comment by seanlandsman** [comment]
I've released ag-grid-react@22.0.0-beta.0 to allow users to test the fix - let me know if this works for you.

**Comment by seanlandsman** [comment]
I found an issue with the umd bundle - fixed in 22.0.0-beta.2

**Comment by dcjones1** [comment]
I should clarify my exact problem as my original comment was unclear. 

Reordering of columns works perfectly well for me. When I move a column from pinned to unpinned or the other way around, that's when I lose all content. I've even tried a simplified version where I only display a div with some text inside my custom header and it still loses content when the pinning status changes.

I've utilized a code sandbox to determine that my issue comes from some type of clash with the material-ui package, specifically with styling. I found that I could wrap my styled material-ui component with a component that simply renders the styled one and this has resolved it completely for me.  

Thank you for your work on the issue, as it gave me the right direction to resolve my particular case.

**Comment by DominicTobias** [comment]
I'm getting this on incredibly simple renderers - 

```js
import { Link } from 'react-router-dom';

function issueLinkRenderer({ value }) {
  if (!value) {
    return null;
  }

  return <Link to={`/issues/${value}`}>{value}</Link>;
}
```

How is that not rendered in 1s?

**Comment by seanlandsman** [comment]
@DominicTobias Can you try with ag-grid-react@22.0.0-beta.2 and let me know if this resolve the problem for you?

**Comment by DominicTobias** [comment]
@seanlandsman It may have fixed an issue, however mine was still happening but I realised it's because of the `return null` - AG thinks the component hasn't rendered. I've change it to this now and it works:

```js
function roadmapLinkRenderer({ value }) {
  if (!value) {
    return ''; // null breaks AG's logic to determine if component is rendered (bug).
  }

  return (
    <Link to={`/roadmap/${value}`} title="Explore in Roadmap">
      <FaAlignCenter size="18px" />
    </Link>
  );
}
```

I put the checks in because the renderer is still called on empty rows after doing a filter (e.g. filtering returns 3 rows but render is called on all visible rows so an icon was rendering on them)

**Comment by aravindsagar** [comment]
I'm seeing this error on custom filter components, but only when using a custom floating filter component which calls `currentParentModel` or `parentFilterInstance` before the filter component is mounted.

Reproducer: https://next.plnkr.co/edit/OLWOxTRv8aaVU1s6

Commenting out lines 23-26 avoids the error. I'm using ag-grid-react@22.0.0-beta.2

**Comment by seanlandsman** [comment]
@aravindsagar - thanks for reporting this, I'll make sure it's fixed for 22.0.0 (out next week)

**Comment by seanlandsman** [comment]
@DominicTobias @aravindsagar Having taken a look at this I'm afraid it won't make the cut for 22.0.0, but I'll endeavour to get this into a patch release in the next few weeks.

I'll keep you updated with regards to progress

**Comment by Agedjus** [comment]
Hi guys,

I just updated to 22.0.0 and I was not using nextReact before. Now that this is true by default, I started to get all these errors on my application.

After some research, I figured out that is because my custom cell renderers were defined as memoized functional components. For some reason they don't fit well with AgGrid.

Just as an input for others, my solution was to remove memo(...) from these components and everything works great now. Actually I don't know if AgGrid will take care of this scenario but at least we can avoid the situation in the meantime.

**Comment by seanlandsman** [comment]
@Agedjus do you have a repo I can take a look at? At the minimum I'll update the docs to reflect this.

Thanks for letting me know

**Comment by Agedjus** [comment]
@seanlandsman I don't have a public repo but I can give you an example of it.

**Not working**
`
const BooleanRenderer = memo(({ value }: IBooleanRendererProps) => (
  <>
    {value ? <Icon icon={IconNames.TICK} /> : null}
  </>
));
`

**Working**
`
function BooleanRenderer({ value }: IBooleanRendererProps) {
  return (
    <>
      {value ? <Icon icon={IconNames.TICK} /> : null}
    </>
  );
}
`

I assume it will work just removing memo wrapper and keep the component as an arrow function but I didn't try.

**Comment by seanlandsman** [comment]
@Agedjus thanks - I'll investigate and let you know

**Comment by Paul6552** [comment]
I am not using react-next and get this error:
[Here is a codesandbox example](https://codesandbox.io/s/ag-grid-practice-qg5nk)

Double click on any birthday cell and you get the error

**Comment by seanlandsman** [comment]
@Paul6552 I think you may have provided the incorrect example.

But on the reactNext note - note that with ag-Grid 22.x we only support React 16 and so the reactNext flag has been removed as this is the default behaviour now

**Comment by seanlandsman** [comment]
Also, I appreciate the feedback here - I believe we've covered most use cases, but I'm more than happy to fix use cases considered.

**Comment by aravindsagar** [comment]
@Paul6552 Check out https://www.ag-grid.com/react-hooks/ to see how to use function components as cell editors. If you add `useImperativeHandle` to provide the `getValue` function, your example works fine.

**Comment by Frost-Zhao** [comment]
@seanlandsman 
This problem may still exist in other browsers. I updated the ag-Grid to 22.0.0 and then reappeared this problem in other browsers.
These browsers I have tested:

- Firefox(macOS&Windows)
- Safari
- Edge
- IE11 on win10

There is no problem after the ag-Grid is rolled back to 21.2.2.

**Comment by seanlandsman** [comment]
@Frost-Zhao do you have an example of this? So far I've been unable to reproduce this issue

**Comment by seanlandsman** [comment]
@Agedjus I've raised AG-3600 for this issue and fixed it. It'll be available in our next release, currently scheduled for 6 Dec

**Comment by Frost-Zhao** [comment]
```tavascript
import React, { useState, ChangeEvent, FunctionComponent, FC } from "react";
import { AgGridReact } from "ag-grid-react";

interface ICustomTableHeaderProps {
  displayName: string;
  column: { colDef: { hasChildrenTable : boolean } };
}

const CustomTableHeader: FC<ICustomTableHeaderProps> = (
  props: ICustomTableHeaderProps
) => {
  const { displayName, column } = props;
  const { colDef } = column;

  if (!colDef.hasChildrenTable) {
    return <div className="custom-header-cell">{displayName}</div>;
  }
  return (
    <div
      className="custom-header-cell clickable-custom-header-cell"
      onClick={(): void => {
        window.location.hash = colDef.childrenTableId;
      }}
      role="link"
      tabIndex={0}
      onKeyPress={(): void => {}}
    >
      {displayName}
    </div>
  );
};

      <AgGridReact
        domLayout="normal"
        columnDefs={headersData}
        groupHeaderHeight={38}
        suppressCellSelection
        rowData={rowData}
        frameworkComponents={{ agColumnHeader: CustomTableHeader }}
        pagination
        localeText={{
          noRowsToShow: " "
        }}
        rowHeight={37}
        headerHeight={60}
        suppressPaginationPanel
        suppressPropertyNamesCheck
        onModelUpdated={(event: ModelUpdatedEvent): void => {
          event.api.paginationSetPageSize(pageSizeForAgGridReact);
        }}
        onGridReady={(event: GridReadyEvent): void => {
          props.onGridReady(event);
        }}
        suppressScrollOnNewData
      />
```

@seanlandsman 
Sorry, we have a privacy policy and I am unable to provide detailed source code.
I have extracted the above code and hope to help.
By the way, the `CustomTableHeader` component has no other changes, just a direct reference to the above code.
If there are other needs, I will try my best to help.

**Comment by aravindsagar** [comment]
Still seeing the [issue](https://github.com/ag-grid/ag-grid/issues/3222#issuecomment-550465566) when both floating filter and filter react components are used. 
Updated https://next.plnkr.co/edit/OLWOxTRv8aaVU1s6?preview to use ag-grid 22.1.0

**Comment by seanlandsman** [comment]
@aravindsagar although the title is a little different this issue is covered by AG-3200

You can track it's progress in the pipeline here: https://www.ag-grid.com/ag-grid-pipeline/

We're looking at fixing this in our next major release

**Comment by aravindsagar** [comment]
@seanlandsman Thanks for the update!

**Comment by TylerKienVu** [comment]
This fixed my issue for anybody else who may have been getting this. I was returning null for some cell renderers and as a result, ag-grid was throwing an error.

> @seanlandsman It may have fixed an issue, however mine was still happening but I realised it's because of the `return null` - AG thinks the component hasn't rendered. I've change it to this now and it works:
>

**Comment by chety** [comment]
I also had same problem. I had a columDefs and one of my column has a cellRendererFramework like below(1). In DetailRenderer  i was checking if params is null or params.node is group i return null(2). Instead of returning null , i returned empty string and that solved my problem :) 
kudos to @DominicTobias 

(1)
```
{
    headerName: "Detail",
    field: "detail",
    cellRendererFramework: DetailRenderer,
  },
```
(2)
```
  if (!params || params.node.group || params.value == null) {
    return "";
  }
```

**Comment by hoop71** [comment]
Returning an empty string removed my error as well.

**Comment by jaredharris** [comment]
Can confirm, empty string worked. Weird that <></> didn't.

**Comment by seanlandsman** [comment]
@jaredharris have you tried this with 23.0.0 - it should have obviated the need to use empty strings - <></> and nulls should be dealt with correctly

If not please do let me know

**Comment by lavor** [comment]
I can confirm, that returning `null` from component that is wrapped with HOC `injectIntl` from `react-intl` reports:
`React Component 'WithIntl' not created within 1000ms`

```js
// just demonstration example, it can be changed to functional component, injectIntl can be replaced with useIntl, ...
import * as React from 'react';
import PropTypes from 'prop-types';
import {injectIntl} from 'react-intl';

class LabelFormatter extends React.PureComponent {
    render() {
        const {intl, value} = this.props;
        return value ? (
            <div>
                {intl.formatMessage({id: value})}
            </div>
        ) : '';
    }
}

LabelFormatter.propTypes = {
    value: PropTypes.string
};

LabelFormatter.defaultProps = {
    value: undefined
};

export default injectIntl(LabelFormatter);
```

But when the wrapped component returns `''`, the console error does not appear.

react-intl@4.5.2
ag-grid-community@23.1.0
ag-grid-react@23.1.0

**Comment by seanlandsman** [comment]
thanks @lavor  - I'll take a look

**Comment by bmunnabe** [comment]
I am using cell renderer to render component but getting same error

        { 
          field : 'data',
          cellRenderer: 'checklistItemRow2',
        }

agGridReact.js:138 ag-Grid: React Component 'ChecklistItemRow2' not created within 1000ms

**Comment by pitops** [comment]
Still having the same issue. If I render an empty div it seems to solve the issue.

**Comment by domipieg** [comment]
Hey, I can still encounter this issue while using both: custom floating filter and custom filter. Sometimes custom filter loads without problems, but sometimes when I refresh the page error appears: "react Component '...' not created within 1000ms" in dev tools. So it is completly non-deterministic behaviour.

**Comment by aravindsagar** [comment]
Still exists in version 24.0.0. If we use both custom floating filters and filters, filter component doesn't load and logs this error. Custom filter doesn't open even when the column/filter button is clicked.
Reproducer: https://stackblitz.com/edit/ag-grid-react-hello-world-1irrqr

Commenting out line 42 (to remove custom floating filter) removes the error, and filter component opens if column menu is clicked.

**Comment by biels** [comment]
This issue is still present in 24.0.0, and I'm not using custom filters, only react framework cell renderers

**Comment by domipieg** [comment]
I've found a solution @aravindsagar here is your code with my solution. Don't use this.props.parentFilterInstance or currentParentModel in constructor/componentDidMount/render, when I use it on click, when everything is already loaded then it works :)

https://stackblitz.com/edit/ag-grid-react-hello-world-qupuvt?file=index.js

**Comment by nj314** [comment]
Found another workaround: if your custom component doesn't already expose a `ref` handle, add one - and make sure it returns a truthy value. The Portal won't notice that the component has actually rendered until the imperative handle returns something truthy.

AG Grid Version: 21.2.0

```jsx
const MyComponent = () => <span>Hello world</span>;  // error: React Component not created within 1000ms

const MyComponent = forwardRef((props, ref) => {
  useImperativeHandle(ref, () => ({})); // important: second arg must return something truthy
  return <span>Hello world</span>;
}); // works!
```

This is because `AgGridReact.prototype.waitForInstance` looks for a truthy return from `getFrameworkComponentInstance` to determine whether or not the component has rendered, but functional components don't expose refs by default.

**Comment by fgblomqvist** [comment]
@nj314 That's not a workaround, at least not for filters (maybe you're talking about cell renderers). For filters, it's in the ag-grid spec that you need certain methods, and since you need methods, you'll need `useImperativeHandle` to return them. This applies to both Floating and Standard filters.

I can only second what @aravindsagar is saying (his example is a great one). We call `currentParentModel()` on floating filter mount, however, it works 90% of the time. However, the other 10% the parent filter isn't initialized yet and therefore things break. The race condition seems to be triggered when the grid/browser is dealing with some really heavy loads. E.g. we can trigger it 50% of the time when we side-scroll quickly (so that another 10-20 columns get loaded).

Looking at the source code for this stuff (e.g. the floatingFilterWrapper), it's not too surprising this issue still exists. It seems like the issue is either in [this function](https://github.com/ag-grid/ag-grid/blob/b62eae1af374bdc2fab278f04c77cce131096be9/community-modules/core/src/ts/filter/filterManager.ts#L374) or in the code it's calling. Do note that it fails no matter if `createIfDoesNotExist` is true/false.

To make things a bit more sane and react:y/modern it would probably be useful to make these changes (if possible):

* Pass the current parent model as a prop to the floating filter instead of sending it imperatively (which is an anti-pattern)
  * If you did this, you'd quickly realize that there's a bug somewhere that prevents the parent filter from mounting if you call `currentParentModel()` right as the floating filter is mounted (which should be done so that the floating filter has the right model from the start)
  * You can obviously keep things imperative in your codebase if you want, but it would be a lot easier to create custom filters if we got the model as a prop (that would stay updated, like all React props)
  * Worst case scenario, at the very least, trigger the `onParentModelChanged` once the parent filter has initialized
* [Stop turning a promise into a callback](https://github.com/ag-grid/ag-grid/blob/master/community-modules/core/src/ts/filter/floating/floatingFilterWrapper.ts#L221), promises are easier to deal with (async/await) and look better 😄

**Comment by nj314** [comment]
> @nj314 That's not a workaround, at least not for filters (maybe you're talking about cell renderers). For filters, it's in the ag-grid spec that you need certain methods, and since you need methods, you'll need `useImperativeHandle` to return them. This applies to both Floating and Standard filters.

@fgblomqvist Indeed, there are lots of reasons to `useImperativeHandle`, especially in filters. This issue manifested for me in cell renderers and a custom tool panel, where I had no need to use the ref to expose anything back to AG Grid. It turns out that this means the `ref` is `undefined`, and AG Grid interprets that to mean that the component was not created. Exposing something truthy in `useImperativeHandle` resolved the issue for my cell renderers and custom tool panel.

> Pass the current parent model as a prop to the floating filter instead of sending it imperatively (which is an anti-pattern)

FWIW I completely agree with your critique of the custom filter API. The parent filter model and instance should be each provided via props, even if they're initially `undefined`, and the props should update when changes occur. The responsibility of implementing such a change would logically fall to `ag-grid-react`, so perhaps we should move this discussion there. In the meantime, I have several custom filters to maintain so I ended up writing a base component for them to manage some of the gotchas you mentioned.

As an aside, ag-grid's React API shows little regard for React conventions in general. As another example, the grid never updates the `value` prop to custom cell renderers - instead, the grid currently delegates updates to the `ICellRendererComp.refresh()` callback, which considered an anti-pattern.

**Comment by wangbigmountain** [comment]
Found a workaround. Call `refreshHeader` in `onGridReady`.  This is heavy but useful.

**Comment by vaynevayne** [comment]
reproduce in 29.x
