### ISSUE TITLE
multiple api calls in server side row model.

### ISSUE THREAD

**Issue by hammad-zia-95** [ag-grid/ag-grid#3628]
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'

**Providing a Reproducible Scenario**

Here is the plunkr link to reproduce this bug.

https://plnkr.co/edit/lUNpNvNx6K8f9e0Rqe2j?p=preview
Source: https://www.ag-grid.com/javascript-grid-server-side-model-grouping/

**Steps to reproduce:**

- Group by Country.
- Apply a filter on age column.
- Click the extract layout button on the top.
- Reset columns by pressing the built-in reset column option on any column.
- You will notice that the alert popup appears 4 times. This is called in the getRows() method.
- Now click on apply layout.
- You will notice that the alert popup appears 5 times (If only grouping is applied without filtering the popup will appear 4 times). This is called in the getRows() method.

**Current behavior**
I am using ag-grid to persist layouts (column, filter, sort, group state etc) and then apply it at a later stage using the server side row model. I am dealing with millions of records, therefore whenever a layout is applied by using these grid api functions:

```
 - gridColumnApi.setColumnState(...)
 - gridApi.setSortModel(...)
 - gridApi.setFilterModel(...) 

```

**getRows() method of IServerSideDataSource is called multiple times (5 times to be precise)**. This behavior can be easily reproduced on plunkr which is given in the above section.

Similarly, whenever row grouping is applied and then **reset columns** option is pressed, **getRows() method of IServerSideDataSource is again called 4 times.**

**Expected behavior**
- First of all, whenever a layout containing row groups is applied, **getRows() method should be triggered once only as opposed to 4 times.** 

- Secondly, whenever grouping is applied and columns are reset using the built-in reset column options, **getRows() method should be triggered once only as opposed to 4 times.**

- Lastly, there should be a mechanism to stop the automatic trigger of getRows() method specially when layouts are being set using 

```
 - gridColumnApi.setColumnState(...)
 - gridApi.setSortModel(...)
 - gridApi.setFilterModel(...) 

```
After all the above mentioned models are set, there should be a way to manually trigger the getRows() method with page number 1 which will ensure that only a single call is initiated. Since i am dealing with **a large amount of data, multiple calls with the same page number (page 1) upon setting layout state (specially when grouping is applied) to server side data source is an overwhelming overhead**.

Operating system: 
Windows 10
IDE: VS Code

* **ag-Grid version:** ag-grid-enterprise": "22.0.0"

* **Browser:**
Google Chrome v79.0.3

* **Language:** 
Angular v8.2.14
TypeScript v3.4.5

**Comment by usman-anwar-techverx** [comment]
I am also facing the same issue, tried many solutions but couldn't get around.
Please @ag-grid can you have a look at this.
It will be a great favor.

**Comment by Talhafayyaz11** [comment]
Same issue :(

**Comment by AhmedAGadir** [comment]
Hi,

ag-grid staff does not provide support through github. If you are a customer please contact us through our official support channel. Note that this issue has been flagged as managed-by-the-community, we also recommend you to check stackoverflow, note that if there is no activity on this issue after a while we will close it.

Thanks

**Comment by lattimoregay** [comment]
Given that this is a show stopper in many scenarios, i.e. it generates a bigger load on the services layer and also on the database side, this should be addressed by ag-grid rather than leave it to the community, in essence there is no work around as the calls are being generated deep inside the ag-grid code.  Also as consumers of ag-grid it would be appreciated that we are given more than just look at stack overflow, perhaps a link to possible solution.

**Comment by abhimediratta** [comment]
@hammad-zia-95  You can use `blockLoadDebounceMillis=500`, to try to deal with it. It solved the issue for me.

**Comment by usman-anwar-techverx** [comment]
Thanks a lot @abhimediratta, the `blockLoadDebounceMillis=100` actually solved the issue of multiple calls.
@ag-grid team could have been more responsible by pointing us in right direction in the first place.

**Comment by Vijay-P1999** [comment]
issue still existing, `blockLoadDebounceMillis=500` didn't help.

**Comment by AndrewGlazier** [comment]
Hi @Vijay-P1999, you may be experiencing a bug which was fixed in v29.2.

The issue in question was:
AG-8102 - SSRM - Old datasource requests still fired when datasource changed

Please try to update to v29.2, if this does not fix your issue please open a ticket to report your issue.

**Comment by ishaiavrahami** [comment]
https://github.com/ag-grid/ag-grid/assets/33962719/5e8800f3-002f-467a-a211-4f236d9bd02a

Im getting this behaviour, how can i fix it
