### ISSUE TITLE
Somestimes the filter popup closes unexpectedly

### ISSUE THREAD

**Issue by benceHornyak** [ag-grid/ag-grid#4086]
**I'm submitting a bug report** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
1.  go to [https://plnkr.co/edit/LJR0rofO3IYF7GOv](https://plnkr.co/edit/LJR0rofO3IYF7GOv)
2. make sure you have to scroll and scroll to the very end
3. filter for bronze equals 3
4. filter popup closes

**Current behavior**
If the user has to scroll to the `colDef` the filter popup disappears after filtering to anything. It happens to custom filters as well as built-in filters. 

**Expected behavior**
The filter popup shouldn't disappear. It should stay open. E.g.: in the plunker try to use `Country` filter

**Please tell us about your environment:**

* **ag-Grid version:** 24.0.0

* **Browser:**

Latest firefox: "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0"
Latest Brave browser: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36"
* **Language:** [all]

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment]
Hello!

Thank you for reporting this - much appreciated!

We have reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
AG-4652 [Regression] For columns initially out of view, filter popup disappears by itself after filter value is entered

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can check whether this item is selected for implementation by taking a look at the NEXT RELEASE tab of the product pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

I would recommend signing up for automatic release notifications using the instructions here. Then, following a release, check whether the item was implemented by looking for it in the changelog page.

Thanks again for bringing this up.

**Comment by benceHornyak** [comment]
Hi @makinggoodsoftware,     
I upgraded to version @24.1.0, but the issue is still present. I wonder why this was closed

Thanks

**Comment by kiril-matev** [comment]
Hi BenceHornyak,

Thanks for getting back to us.

You are correct - AG-4652 is not yet addressed and is present in ag-Grid v24.1.

You can see it in our development pipeline under the BUGS tab here (please search for 4652 in the search box above):
https://www.ag-grid.com/ag-grid-pipeline/

We are continuing to track this as an outstanding bug. We will fix this issue as part of an upcoming release.

Thanks again for following this.
