### ISSUE TITLE
Default valueGetter "getValueUsingField" is inconsistent with empty strings

### ISSUE THREAD

**Issue by fgblomqvist** [ag-grid/ag-grid#4120]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**
The default valueGetter for columns with a `field` specified is `getValueUsingField`. It just returns the plain value for non-nested fields (correct) but uses a function called `missing` to determine what to return for nested fields:
https://github.com/ag-grid/ag-grid/blob/f011ffb0ad989acc9e43c9eb075c98e01e264668/community-modules/core/src/ts/utils/object.ts#L194

`missing` is currently defined as: If the value is null or an empty string, it is missing
https://github.com/ag-grid/ag-grid/blob/f011ffb0ad989acc9e43c9eb075c98e01e264668/community-modules/core/src/ts/utils/generic.ts#L11

This is inconsistent. It should allow empty strings. If you want to offer a feature that allows people to normalize empty strings into nulls you can obviously do so, but it should most certainly not be the default behavior imo.

**Expected behavior**
`missing` should propagate the `allowEmptyString` parameter from `exists` and `getValueUsingField` should in turn pass `true` for `allowEmptyString`.

**Comment by fgblomqvist** [comment]
I also want to throw a comment out there that it's quite distasteful how corporate this once-open-source project has become. In normal circumstances, I'd be happy to submit a PR for something like this (and for the many many other non-blocking bugs or incorrect types), but since you're nowadays notorious for not caring about your community I'm gonna refrain from it. The fact that you aggressively (through your stale bot) silence every single issue and PR that gets posted instead of leaving actual issues open until they've been fixed, is just sad. Clearly no one expects you to fix/implement things for them for free, but you are clearly opposed to people helping you fix things as well. I'd suggest you perhaps stop allowing people to post issues, instead of abusing the good-will of people just to filter out the 1-out-of-a-100 bugs/features that you want to actually deal with to satisfy your enterprise customers.

**Comment by makinggoodsoftware** [comment]
Hi There!

I am head of Customer Services at ag-grid.

First, let me say that I am sorry to hear about your disappointment! 

Note that we don't try to silence anything...

> The fact that you aggressively (through your stale bot) silence every single issue and PR that gets posted instead of leaving actual issues open until they've been fixed, is just sad

What we do is, we prioritize the support that we give to our paying customers, and through github we look and fix bugs.

Support requests and Feature requests are not attended as we give priority to our customers.

We do make public everything that is in our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/ 

And in our changelog:
https://www.ag-grid.com/ag-grid-changelog/ 

In there you can see all the bugs open, and every single bug that has been raised with a reproducible scenario through this channel has been added there and fixed.

In this view here you can sell all issues that have been investigated:

https://github.com/ag-grid/ag-grid/issues?q=is%3Aissue+label%3Ain_zendesk+

Note that there are 170 issues there

I hope this makes sense.

**Comment by artu-ole** [comment]
Since you decided to touch on that yourself:

> and through github we look and fix bugs.

That is in fact a blatant disinformation as the number of bugs(not feature requests, not questions - bugs) that just get stamped with "ag-grid staff does not provide support through github." without acknowledgment being auto closed thereafter is overwhelming.
We did consider to use ag-grid in our product, but after seeing the amount of red flags this repository throws with the state of community and it's management transparency it's a no go. I do hope in the years to come something clicks into place regarding this before it's too late for the product.

Not to mention that if you have 18 bugs and 507 "feature requests" in your pipeline it does not mean that you have a bug free software - it merely means you don't know a definition of a bug.

YMMV, I do have [own horse in the race](https://github.com/ag-grid/ag-grid/issues/4121).

**Comment by fgblomqvist** [comment]
@makinggoodsoftware Thank you for at least taking the time to manually write a response, appreciate it. However, I must agree to disagree with you with regards to the statement that you do fix all the bugs that have reproducible scenarios. First of all, having a reproducible scenario should not be a requirement. There are many issues that get closed that simply point out in the code where a bug exists, and sometimes even how to fix it. Any engineer would be able to read that and immediately realize that "oh shit, this is indeed not correct".

Similarly, **over half** of all closed PRs did not get merged, and tons of those did not even receive a single comment from you guys, despite them being obvious fixes. Not even when they correct spelling mistakes or incorrect docs! Like what on earth?! Why would you have a PR feature if you don't even want PRs? I come across inconsistencies in the docs every week and lose valuable time to it, and I can guarantee you that I am not alone. I'd be happy to fix those but why should I bother when the odds of anyone here caring is far from in my favor?

To me, you're just hiding behind a series of excuses to not have to spend time on your community because I guess someone at your company ignorantly believes that such time is not worth it. Imagine how many bugs and docs issues the community could have helped you with by now if you would have cared? That's **free** labor. Even if you don't prioritize features and support for non-customers, why don't you at least let the community handle it?

* Instead of closing an incomplete issue, request more information and leave it open for others to join in and collaborate (eventually it might become complete enough to where you will work on it, or perhaps someone from the community will submit a PR).

* Make sure you at least respond with a single sentence to every PR that you close without merging, stating the reason to why you didn't merge it. That's common courtesy.

* Stop spamming your own issues with useless comments saying that you don't provide support here. Just leave them be instead, people will understand.

It just saddens me that a fellow European, and even worse, a company based in Europe, shows such disregard for collaboration 🙁 I don't know if you work as an engineer as well, but if you don't, then I don't blame you for not understanding the things above. Instead, I'd strongly advise you to talk to an engineer at your company and see what they say about all this. Very few engineers I've met dislike open source collaboration.

**Comment by makinggoodsoftware** [comment]
Hi guys!

Thanks for all the feedback! We are taking this on board!

Before anything else, let me assure you guys that whatever your impression is of ag-grid as a company is nothing like what I can see you guys describing there, but this means to me that we are not doing a good job with comms on github MY BAD!

ag-grid is basically a company formed by a bunch of programmers, me including! And being part of the open-source community is something we take very seriously!

From today I will make sure that we do a better job replying to the github issues!

> - Instead of closing an incomplete issue, request more information and leave it open for others to join in and collaborate (eventually it might become complete enough to where you will work on it, or perhaps someone from the community will submit a PR).

Will do!

> - Make sure you at least respond with a single sentence to every PR that you close without merging, stating the reason why you didn't merge it. That's common courtesy.

Will do!

> - Stop closing PRs and fixing the issues yourselves. Why not just save yourself the work and give people some credit for actually taking the time to fix it? It literally takes you a minute to merge something.

Will raise this, the problem we have with the PRs is that our build is not easy to run, so that is why we do it manually

> - Stop spamming your own issues with useless comments saying that you don't provide support here. Just leave them be instead, people will understand.

Will do!

---

It was never our intention to create a barrier with the community! Quite the opposite, so we will try to do better.

Hope this makes sense,

We will start processing the tickets like I just announced today.

**Comment by kiril-matev** [comment]
Hello!

Thank you for reporting this.

We agree with the observation you've made and will treat this behavior as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-4708 Default valueGetter for columns with a field specified doesn't support empty strings**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can check whether this item is selected for implementation by taking a look at the NEXT RELEASE tab of the product pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

I would recommend signing up for automatic release notifications for ag-Grid. Then, following a release, check whether the item was implemented by looking for it in the changelog page.

Thanks again for bringing this up with us.

**Comment by fgblomqvist** [comment]
Thank you so much for the reasonable response, I appreciate you guys taking this seriously 🙂 
I'm sure everyone will benefit from this long-term!

> Will raise this, the problem we have with the PRs is that our build is not easy to run, so that is why we do it manually
I see. Yeah I mean I'm sure something can be done. Perhaps making a `CONTRIBUTE.md` with some instructions on how a PR needs to be done to get accepted (just an idea).

**Comment by makinggoodsoftware** [comment]
Hi,

I Hope is all good there! Just updating this a few days later the announcement regards changing the approach to support on gitHub.

We still not have an update with regards to the pull requests, but I am hoping to change the way we process them by next week!

With regards to the issues, we have new labels and we are continuing with the actions as described in my previous comment,.

Thanks again for the feedback

**Comment by makinggoodsoftware** [comment]
Hi There!

Took longer than expected, but we have finally gone full circle including the PRs for the revamp of support that we give through GitHub.

We will be looking to intake PRs automatically, at the moment is manual, but we will inform of this, and I have just updated the currently only one opened that was applicable.

I will leave this open for a few more days to let you guys provide feedback, from our end, we have taken on board the suggestions. I hope this makes a difference!

Thanks

**Comment by fgblomqvist** [comment]
Thank you for revamping the process! It's obviously too early to judge fully but should be interesting to see how PRs in the coming months go.

**Comment by makinggoodsoftware** [comment]
Hi guys,

I think is fair to close this issue now, but by all means feel free to follow up, note that you will get much more visibility if you create a new issue as it will get our attention.

Thanks for your feedback
