### ISSUE TITLE
[24.1.0] Strange column re-arrange

### ISSUE THREAD

**Issue by benceHornyak** [ag-grid/ag-grid#4166]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Some what reproducible: https://plnkr.co/edit/yuoPiJFMhjACGtfK

**Current behavior**

![image](https://user-images.githubusercontent.com/12515595/97464608-6a2f8580-1941-11eb-8859-0a832469e51b.png)

After 1-2 seconds:

![image](https://user-images.githubusercontent.com/12515595/97464655-7a476500-1941-11eb-9403-f26ff9b73bd2.png)

**Expected behavior**

Shouldn't re-arrange itself whatsoever. After downgrading to version 24.0.0 it worked as before, but I'd love to upgrade the version without breaking things. 

* **ag-Grid version:** 24.1.0

* **Browser:** All

* **Language:** [all]

**Comment by makinggoodsoftware** [comment]
Hi,

Could you clarify the steps to reproduce your issue using your provided plunker?

Thanks

**Comment by zackthoutt** [comment]
We ran into a similar issue. The problem seems to be related to the colID. We have a set of buttons that allow the user to change what data is displayed. The column headers stay the same, but the background data and field change. We were getting odd behavior where the order of the columns would match up with the columnDefs order when initially rendered, but after pressing the buttons to change the background data, the order would scramble. 

I was able to fix this issue both by reverting to 24.0.0 and by manually adding a colId to each column definition that stays consistent even when the field changes.

**Comment by benceHornyak** [comment]
@zackthoutt Can you please try to reproduce your issue? Sounds very similar to ours, but I'm not really sure how to reproduce with a clean environment.

**Comment by zackthoutt** [comment]
I don't have time to work through a clean reproduce right now, but I suspect that if you:

1. Define the grid data to have, say, 100 field with random data
2. Set the columnDefs to display only 10/100 field
3. Add a button that randomly chooses a new set of 10 fields and refreshes the columnDefs

If you do this, I think you'll see that the order of the columns in columnDefs will match the order displayed in the grid on the first render, but as you press the button to randomly choose 10 fields to show, the columns will start to scramble and get out of sync with the order they are defined in columnDefs. 

The way I fixed it was to add my own colId to each column. I think something in 24.1 changed the way colId is assigned by ag-grid if it isn't explicitly defined.

**Comment by benceHornyak** [comment]
@makinggoodsoftware I was able to create an another plunkr: https://plnkr.co/edit/TdeyCWGmEpW4JRcV?preview 
let me if this better. You have look really close for the name floating filter to catch it. I'm not sure how to make the rendering slower.

**Comment by makinggoodsoftware** [comment]
Hi,

I am afraid that I can't still see any odd behavior on that plunker, would you be able to advise if we should use a particular browser/OS?

Does this always happen on your end?

Could you make a screen recording?

**Comment by benceHornyak** [comment]
![Peek 2020-11-17 16-02](https://user-images.githubusercontent.com/12515595/99406588-59de4b00-28ee-11eb-8253-48088e2f3061.gif)

There is a jump after loaded. 

Latest Brave-stable browser and also checked latest firefox

**Comment by makinggoodsoftware** [comment]
Hi,

Thanks for that! I understand now what you mean... That is just how it is rendered...

I am afraid that we would not see this as a bug... 

I would say that the flickering is pretty much unnoticeable, wouldn't you agree?

**Comment by dprentis** [comment]
We are also experiencing a column ordering issue - columns are displayed in seemingly random order irrespective of the order given in `columnDefs`.

The user switches between different grid views using a dropdown. The order of the displayed columns for a given view changes every time the grid for that view is rendered, whilst the order of the columns defined in `columnDefs` remains the same.

It is not just a 'flicker' - the order of the columns remains wrong, the whole time the grid is displayed.

**Comment by benceHornyak** [comment]
Exactly. There is something funky going on with the colDefs, I'm not sure how to reproduce it better in a clean environment, but I'll definitely have to spend more time in the future to reproduce it. 

This is very noticeable on our side. This is a blocker to update our ag-grid version.

**Comment by dprentis** [comment]
I took @zackthoutt 's advice and set the `colId` for each column definition, using the form:
```
`col${`00${idx}`.slice(-3)}`
```
Where `idx` corresponds to the index in `columnDefs`. This appears to ensure the columns are rendered in the correct order.

**Comment by makinggoodsoftware** [comment]
Hi,

The colIds are the best option to provide if you do update colDefs...

https://ag-grid.com/javascript-grid-column-updating-definitions/#matching-columns

@benceHornyak Note that in v24 the order of the columns is not changed when you call setColumnDefs, this is done to prevent overriding changes the user might have done on his end on the columns.

You can configure this though:

https://ag-grid.com/javascript-grid-column-updating-definitions/#applying-column-order

Can you guys let me know if this helps?

**Comment by dprentis** [comment]
Thanks @makinggoodsoftware - the `applyColumnDefOrder` prop works too :+1:

**Comment by benceHornyak** [comment]
Just as an FYI; this turned out to be a problem with our code, after a lot of refactor, debugging we finally figured it out and we were able to upgrade to v25.0.1. Thanks @makinggoodsoftware
