### ISSUE TITLE
Vue3 Cell Renderer Setup() method not running

### ISSUE THREAD

**Issue by Declan-Watts** [ag-grid/ag-grid#4221]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[x] support request => see 'Requesting Community Support'
```

I am using Vue 3 and trying to use a cell renderer for an Edit button within an Actions Column. But it seems asif the Setup method is not working when it is being included via the Cell renderer. However, if I include the Component straight into the page it works fine.

This is the error I am getting

```
Uncaught TypeError: Cannot read property 'apply' of undefined
    at Object.onClick._cache.<computed>._cache.<computed> (actionsColumn.vue?df29:4)
    at callWithErrorHandling (runtime-core.esm-bundler.js?5c40:154)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js?5c40:163)
    at HTMLButtonElement.invoker (runtime-dom.esm-bundler.js?830f:292)
```

This is the Component that is being used

```
<template>
  <button
    class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded"
    v-on:click="onEditClick"
  >
    Edit
  </button>
</template>

<script>
  import { computed, defineComponent, ref } from "vue";
  import { mapGetters, useStore } from "vuex";

  export default defineComponent({
    name: "actionsColumn",
    setup() {
      // Setting Up Store
      const store = useStore();

      // Getting SiteData and Route
      const siteData = computed(() => store.getters.siteData);

      // Route and Section
      const route = computed(() => store.getters.getCurrentRoute);
      const section = ref(
        siteData.value.sections[route.value ? route.value : "Home"]
      );

      const onEditClick = () => {
        console.log("Edit");
      };

      onEditClick();
      console.log("editbutton");

      return {
        onEditClick,
      };
    },
  });
</script>
```

This is the Column Def for that column
```
{
        headerName: "Actions",
        field: `${section.value.tableName}_id`,
        cellRendererFramework: "actionsColumn",
      }
```

It is displaying the button in the Grid correctly, it just throws the error when you click the button. The console.log ("editbutton") inside the setup method also is not being run.

Any help would be greatly apreciated

**Comment by laruiss** [comment]
Examples with **vue3** would be greatly appreciated. Especially on how to make the custom CellRenderers aware of the globally registered components, the $store and the $router, with or without the Composition API, since the `Vue.extend()` does not exist in Vue3.

**Comment by Declan-Watts** [comment]
@laruiss Sorry wasn't 100% sure if you were asking me or people who already know for examples.

**Comment by laruiss** [comment]
Sorry, I was not clear. I meant in the docs of ag-grid-vue

**Comment by Declan-Watts** [comment]
Np Yea I agree. There is not much documentation on Vue 3 for AG Grid at the moment. I have managed to get most of AG grid working on vue 3 but currently stuck on this part.

**Comment by laruiss** [comment]
So how did you make your CellRenderers aware of the `$store` and `$router`?

**Comment by Declan-Watts** [comment]
Well, this CellRenderer isn't, that is because it isn't running the setup method on load. hence the issue. Since the setup() is not being run when imported through ag-grid, it doesn't know what store and router are. (Router is not vue-router, I have custom made my own router for this project.) and for $store, you need to use a new version of Vuex, there are some tutorials online for setting $store up. But for cell renderers, I am not sure how to get it to run setup.

**Comment by Maximus1000** [comment]
Also, as Vue.extends ({}) would now be export default {extends: CompName,...}, if we are going to extend agGrid's component like ICellRenderer, docs would be helpful.  No go.  I tried a whole bunch of variations to see if I can figure out how to get access to vue-router (v4) or by way of emit events , failed.  Even with a bunch variations on cellRendererParams when defined within vuex state (all my tables and columnDefs are in vuex, then acting as computed getters in component), struck out.  Can't seem to figure out how to notify the ag-grid component properly of events within a cellRenderer (on this I feel like I just haven't found the answer yet but trying to avoid this.$emit).  Also, looks like comments in a cellRenderer template are a no go (field doesn't render) if anyone encounters this issue (no comments in cellRenderer template).

**Comment by makinggoodsoftware** [comment]
Hi guys,

I can see that there is a lot of traction here, we are looking into this now.

Is there any chance anyone could provide us with a repro that we could get our hands on to see the issues you are seeing on your end?

Thank

**Comment by Declan-Watts** [comment]
> Hi guys,
> 
> I can see that there is a lot of traction here, we are looking into this now.
> 
> Is there any chance anyone could provide us with a repro that we could get our hands on to see the issues you are seeing on your end?
> 
> Thanks

I will get one up soon, and then link it here

**Comment by makinggoodsoftware** [comment]
@Declan-Watts Thanks! 

Looking forward to seeing if we can help with this

**Comment by makinggoodsoftware** [comment]
Hi guys

Given how long this is being opened without a repro, I am going to close it, feel free to open a new ticket if you still see issues around this area, but please add a repro so we can take a look

Thanks

**Comment by Sevenaka** [comment]
how did you solve the problem?

**Comment by jzs11** [comment]
Hey @Sevenaka it ended up I did not use ag-grid.

**Comment by paynezhuang** [comment]
> Hey @Sevenaka it ended up I did not use ag-grid.

I also encountered the same problem
ag grid uses too little documentation in vue3
Have you given up on ag grid? Which one did you choose? Recommend

**Comment by Declan-Watts** [comment]
@paynezhuang I ended up giving up on AG-Grid and switched to Quasar as my UI Library specifically for their Data table. It performs so well and has so much customizability. The only issue is, it is pretty barebones and needs a lot of custom stuff written for it (Filtering etc.). It has great documentation otherwise.

I was meant to get a repo up for this, but unfortunately Work got super busy and we switched what we use to be able to continue working

**Comment by paynezhuang** [comment]
> @paynezhuang I ended up giving up on AG-Grid and switched to Quasar as my UI Library specifically for their Data table. It performs so well and has so much customizability. The only issue is, it is pretty barebones and needs a lot of custom stuff written for it (Filtering etc.). It has great documentation otherwise.
> 
> I was meant to get a repo up for this, but unfortunately Work got super busy and we switched what we use to be able to continue working

I am using Quasar UI now. Later, I found Ag grid for adaptation due to table drag width, right click and other requirements. But now, the overall effect is not very good, and the effect for vue3 support is too bad. I now go to use vxe table

**Comment by Sevenaka** [comment]
> > Hey @Sevenaka it ended up I did not use ag-grid.
> 
> 
> 
> I also encountered the same problem
> 
> ag grid uses too little documentation in vue3
> 
> Have you given up on ag grid? Which one did you choose? Recommend

hi, had to switch to vue2

**Comment by livthomas** [comment]
You don't have to switch to Vue 2 because of this issue. You can simply create Vue 3 components using Options API instead of Composition API.

But it would still be nice if this got fixed. Using Options API in Vue 3 feels like being stuck in the Stone Age.

**Comment by denizcdemirci** [comment]
Any progress on this issue? I need to use composition API in cell renderers but AG Grid doesn't support it. @makinggoodsoftware please tell us the latest updates for this issue.

**Comment by apeling** [comment]
You can use the composition api in cell renderers, but it is janky. The only thing I've found that works is using getCurrentInstance(). The larger issue though is there is no example / or possible way that I have found to use application components / dependencies(vue router, router-link, vuex, other globally registered component, etc) inside of an ag grid cell renderer component. I.E. I would much prefer to use the router-link component in the example below instead of creating an anchor tag.
```
<template>
  <a v-if="url" :href="url" class="grid-link">{{linkText}}</a>
  <span v-else>{{linkText}}</span>
</template>

<script lang="ts">
import {
  computed,
  defineComponent, getCurrentInstance
} from 'vue';
// Ag grid cell renderer support for Vue 3 still isn't quite right.
// Globally registered components also do not work
// params is added to the Component instance (getCurrentInstance) data and is where the cell values are stored.
// params.key is where 'cellRendererParams' defined in a column's columnDef reside
// params.data contains the values for all columns/fields on this cell's row.
export default defineComponent({
  name: 'LinkCell',
  setup() {
    const instance = getCurrentInstance();

    function getParts(): Record<'params'|'data', any> {
      const { params } = instance?.data as Record<'params', any>;
      const { data } = params;
      return { params, data };
    }

    return {
      linkText: computed(() => {
        const { params, data } = getParts();
        const prop: string = params.labelProp;
        const failSafe: string = params.linkLabel ? params.linkLabel : 'View';
        return data[prop] || failSafe;
      }),
      url: computed(() => {
        const { params, data } = getParts();
        const prop: string = params.urlProp;
        return data[prop] ? `#/${data[prop]}` : null;
      })
    };
  }
});
</script>
```

**Comment by seanlandsman** [comment]
A note for everyone here - there were a few issues around the first version of our vue 3 offering. This issue along with others should be fixed with 26.0.0, currently scheduled for the end of next week

**Comment by seanlandsman** [comment]
I should also note that all examples will (alongside JS, react, angular and vue 2) have a vue 3 version. There is also a vue 3 specific getting started guide (again, to be released next week)

**Comment by williamtsanders** [comment]
> A note for everyone here - there were a few issues around the first version of our vue 3 offering. This issue along with others should be fixed with 26.0.0, currently scheduled for the end of next week

Where should we be looking for updates?

**Comment by stevebauman** [comment]
Hmmm, globally registered components still cannot be used in cell renderers v26.0.0. This doesn't appear to be fixed.

**Comment by hloehrmann** [comment]
> You can use the composition api in cell renderers, but it is janky. The only thing I've found that works is using getCurrentInstance(). The larger issue though is there is no example / or possible way that I have found to use application components / dependencies(vue router, router-link, vuex, other globally registered component, etc) inside of an ag grid cell renderer component. I.E. I would much prefer to use the router-link component in the example below instead of creating an anchor tag.
> 

Note from my side: you need to call `getCurrentInstance` in the `onBeforeMount` lifecycle hook, otherwise the params are not available. It also helps to type the params as `ICellRendererParams`.

```
setup() {
    const someValue = ref('');

    onBeforeMount(() => {
      const instance = getCurrentInstance()?.data as Record<
        'params',
        ICellRendererParams
      >;

      const params = instance.params;
      someValue.value = params.value;
    });

    return {
      someValue
    };
  },
```

**Comment by seanlandsman** [comment]
@hloehrmann 

I have just published 26.0.1-beta.1 - do you want to give that a go and let me know how you get on?

the `props` passed into `setup` will have the `params` object on it - it should contain all you need

**Comment by hloehrmann** [comment]
@seanlandsman thanks for the update! 

Just tried it, but `props` is typed as `Readonly<LooseRequired<{}>>` and therefore throwing an error that `params` don't exist when trying to use `props.params`:

`TS2339: Property 'params' does not exist on type 'Readonly {}>>'.`

**Comment by seanlandsman** [comment]
I suspect you'll need to cast it to something that expects `params` - I'm not sure I can enforce/change that from our side

**Comment by seanlandsman** [comment]
Unless you explicity state `params` as a prop on your component I guess - then TS should work as desired

**Comment by seanlandsman** [comment]
I've just tried this locally and could reproduce what you have - if I add `params` to `props` TS is satisfied:

```
<script lang="ts">
    import {defineComponent, ref} from "vue";

    export default defineComponent({
        name: "MyComponent",
        props: ['params'],
        setup(props) {
```

**Comment by seanlandsman** [comment]
> Hmmm, globally registered components still cannot be used in cell renderers v26.0.0. This doesn't appear to be fixed.
> 
> This PR seems like they attempted to resolve the issue: #4601
> 
> But it was closed.

@stevebauman I'll try reproduce this my side - I'll let you know what I find

**Comment by hloehrmann** [comment]
> I've just tried this locally and could reproduce what you have - if I add `params` to `props` TS is satisfied:
> 
> ```
> <script lang="ts">
>     import {defineComponent, ref} from "vue";
> 
>     export default defineComponent({
>         name: "MyComponent",
>         props: ['params'],
>         setup(props) {
> ```
> 
> I'll add this requirement for TS components to our docs to make it clearer

Ok cool, adding it as a non-required prop seems like a good approach. If you type the prop you even get intellisense on it :-)

```
 props: {
    params: {
      type: Object as PropType<ICellRendererParams>,
      required: false,
    },
  }
```

**Comment by seanlandsman** [comment]
thanks for helping verify this @hloehrmann - I'll be issuing a proper patch release either tomorrow or early next week

**Comment by priiduneemre** [comment]
> Hmmm, globally registered components still cannot be used in cell renderers v26.0.0. This doesn't appear to be fixed.
> 
> This PR seems like they attempted to resolve the issue: #4601
> 
> But it was closed.

Since is the only GitHub issue which mentions the above limitation several times, I wanted to clarify: this is still the case, right? 

That is, there is currently no way to call e.g. Vue's `inject()` or vue-i18n's `useI18n()` from the `setup()` body of a custom cell renderer, right?
