### ISSUE TITLE
React Component not created within 500ms

### ISSUE THREAD

**Issue by travikk** [ag-grid/ag-grid#4282]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
https://plnkr.co/edit/6uUkzO8ZWi2GVikU

Open chrome dev console and start fast scrolling through the grid with breaks so that the grid can render the window.
From time to time you'll notice a warning in the console:
`ag-Grid: React Component 'cellRendererFramework' not created within 500ms`

**Current behavior**
Having even a very simple react renderer causes ag-grid not to render it sometimes throwing an error indicated above.
Increasing the timeout to 1000ms by changing the variable on AgGridReact does not help, which indicates it's not the change that switched the threshold from 1000ms to 500ms is causing the issue to occur.
The issue is amplified when using status bar react component. For the grid re-scrolling to the position fixes the issue, but the status bar component can't be recreated.

The issue only started to occur in 25.0.0, when I test my app on 24.1.0 the grid works fine.

**Expected behavior**
React components throughout the grid are rendered properly.

* **ag-Grid version:** 25.0.0

* **Browser:**
"Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36"

* **Language:**
All

**Please note I am enterprise customer but we are not allowed to submit anything through our enterprise channel hence I am using github**

**Comment by miko866** [comment]
The same issue here after updated to 25.0.0.

Browsers: Mozilla, Chrome, Safari

I am enterprise customer.

**Comment by kiril-matev** [comment]
Hi travikk and miko866,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a regression from v24.1.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-4946  [Regression] When scrolling fast vertically, React cell renderer throws console exception "React Component not created within 500ms"**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date. 

You can see whether this item is selected for implementation on the NEXT RELEASE tab of the product pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

I would recommend signing up for ag-Grid new release notifications. This way you'll know as soon as a new version is out and you can check whether this was implemented on the changelog page.

Thank you once again.

**Comment by seanlandsman** [comment]
@travikk @miko866 I've just released a beta release with this fix `@ag-grid-community/react@25.0.1-beta` / `ag-grid-react@25.0.1-beta`

Do you want to try it out and see if it resolves this issue for you?

**Comment by miko866** [comment]
@seanlandsman I have tried and the original error is gone but it comes another issue:

```
Uncaught TypeError: Cannot read property 'dispatchEvent' of null
    at Function.ComponentUtil.processOnChange (ag-grid-community.cjs.js:7269)
    at agGridReact.js:179
```

**Comment by seanlandsman** [comment]
@miko866 do you have a repo I can take a look at?

**Comment by miko866** [comment]
@seanlandsman No, I haven't repo.

**Comment by travikk** [comment]
Hey, sorry for the late reply.

@seanlandsman on the surface looks like `1-beta` addresses the issue. Curious, did you change anything else apart from reverting the timeout to 1s? Because when I monkey patch 500ms to 1000ms on `25.0.0` the issue still occurs, albeit less frequently.

**Comment by BrianHVB** [comment]
I am also getting a `Uncaught TypeError: Cannot read property 'dispatchEvent' of null` after upgrading @ag-grid-community/react from `24.x` to `25.0`.

Condensed Error / Stacktrace:
```

  | ComponentUtil.processOnChange | @ | componentUtil.js:73

  | (anonymous) | @ | agGridReact.ts:207
  | setTimeout (async) |   |  
  | AgGridReact.processPropsChanges | @ | agGridReact.ts:207
  | AgGridReact.shouldComponentUpdate | @ | agGridReact.ts:188
  | checkShouldComponentUpdate | @ | react-dom.development.js:12525
```

I've traced the error to the following change:

v24.1.1
https://github.com/ag-grid/ag-grid/blob/75a4e896cf961911b5b492dd9f3ee2d70c20ebc5/community-modules/react/src/agGridReact.ts#L186

```javascript
ComponentUtil.processOnChange(changes, this.gridOptions, this.api!, this.columnApi);
```

v25.0.0
https://github.com/ag-grid/ag-grid/blob/338ea6d7396bcfbd82b6977a30a89726ca000fe7/community-modules/react/src/agGridReact.ts#L207
```javascript
window.setTimeout(() => ComponentUtil.processOnChange(changes, this.gridOptions, this.api!, this.columnApi));
```

For whatever reason, there are occasions in the newer version where `CompomentUtil.processOnChange` is receiving `null` for the `api` parameter. This is related to the addition of the `setTimeout()` wrapper, as removing it and restoring the `processOnChange()` to a direct call fixes the issue in our codebase.

I'm sorry I can't provide a concise example. In our application, the error occurs after React updates grid data that is stored as state, but I don't know what specific interactions are occurring. My hunch is that a componentUpdate is running in its own thread, and the `setTimeout()` call is losing its closure to the `this` instance that contains a value for `this.api`.

I'm guessing that the addition of the `setTimeout()` (with zero delay) was done to improve render performance, but perhaps the change should be reverted, as I believe it will cause errors in not just our application, but others as well.

I can move this to a new issue if you would like.

**Comment by makinggoodsoftware** [comment]
Hi @travikk the changes were deeper than that, they involved hte way we batch processing of portals - the increase of timeout wasn't the fix here

For anyone else, could we get a repro? From the customer side of support everyone on 25.0.1 saw this issue fixed... 

If you could provide us wit a repro on v25.0.1 where this issue is still there we will have a look

**Comment by makinggoodsoftware** [comment]
Hi guys,

It seems like this is all fixed now in v25.0.1, note that if you see any more issues to open a new issue, as we don't monitor closed issues

Thanks

**Comment by sep2** [comment]
I still encounter this with `"ag-grid-react": "^28.0.0"`
> portalManager.js:75 AG Grid: React Component 'GridNoRowsOverlay' not created within 1000ms

**Comment by kiril-matev** [comment]
Hi @sep2,

Thank you for reaching out.

We're keen to investigate further. 

Please open a new issue with a reproducible scenario for the issue you've described.

Looking forward to working with you!

**Comment by yogesh-datadive** [comment]
@kiril-matev  Im an enterprise user, I am facing this issue on ag-grid version `^30.2.0`, I increased the  `maxComponentCreationTimeMs` to 2500, now I see `React Component not created within 2500ms` instead of solving my issue. What is the suggestion from ag grid team? Please guide me how can i proceed.

**Comment by AG-Zoheil** [comment]
Hi @yogesh-datadive,

Thank you for submitting this on GitHub.

As you've mentioned you are an enterprise client I would encourage you to contact us via our [support portal](https://ag-grid.zendesk.com/) for issues or suggestions. That would be the quickest and most efficient route for you to get your question answered. It would be best to provide a reproducible scenario when you contact us (e.g. a plunker forked from our website documents) so that we can look into it.

Kind regards,
Zoheil
