### ISSUE TITLE
SSRM pagination - endRow not showing after update to v25

### ISSUE THREAD

**Issue by s426231** [ag-grid/ag-grid#4295]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[X] support request => see 'Requesting Community Support'
```

**Current behavior**
After updating ag-grid to v25 I have set serverSideStoreType to partial (as described in the blog article),
the pagination started working, but not at all. The question mark is getting shown, so my pagination looks like:
1 to ? from 92, page 1 of 6
I have gridOptions like:
```
    pagination: true,
    paginationPageSize: 18,
    cacheBlockSize: 18,
    maxBlocksInCache: 1,
    rowModelType: "serverSide",
    serverSideStoreType: ServerSideStoreType["Partial"],
```

    And when I do the console log in datasource getRows() function like :
console.log(params.request.endRow)
it is showing correctly number 18 (for first page of course). But it is not shown in UI. 😢 
This bug also exists in docs:
https://www.ag-grid.com/documentation/javascript/server-side-model-pagination/

**Expected behavior**

I want pagination to looks like:
1 to 18 from 92, page 1 of 6.
**Please tell us about your environment:**
VUE Framework

* **ag-Grid version:** v25

* **Browser:**

* **Language:** [all]

**Comment by pinutz23** [comment]
We currently have the same exact bug. Currently we work around that by adjusting the label manually, since we know all the required information. Of course this is a hack and we are interested in a better solution.

```typescript
  /**
   * Workaround to show the actual number of rows for a given page
   * Issue: https://github.com/ag-grid/ag-grid/issues/4295
   */
  private setLbLastRowOnPage(): void {
    if (!this.gridApi) {
      return;
    }

    const lbLastRowOnPageEl = document.querySelector(`#${this.id} [ref=\'lbLastRowOnPage\']`);
    const isLastPage = this.gridApi.paginationGetTotalPages() === this.gridApi.paginationGetCurrentPage();
    const endRow = isLastPage ?
      this.gridApi.paginationGetRowCount() :
      (this.gridApi.paginationGetCurrentPage() + 1) * this.gridApi.paginationGetPageSize();
    if (lbLastRowOnPageEl) {
      lbLastRowOnPageEl.innerHTML = endRow.toString();
    }
  }
```

**Comment by konttinen** [comment]
We're also experiencing same issue with a vanilla JS/TS implementation. It seems that initially the number is correct, but when the async backend call returns (and the success callback is called) the correct number is replaces by the ?.

**Comment by pinutz23** [comment]
I already had a quick look into that. At first the correct number of rows is shown for a split second, but after that `this.serverSideRowModel.isLoading()` is `true` (and stays `true`), which is why the `?` remains shown.

This is the relevant excerpt in code: https://github.com/ag-grid/ag-grid/blob/master/community-modules/core/src/ts/pagination/paginationComp.ts#L213

**Comment by makinggoodsoftware** [comment]
Hi,

We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs, and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.

To allow GitHub users to provide feedback we are going to flag this ticket as community-engaged, which means that concerns and/or opinions around this feature request are welcomed and you can expect as well to hear back from us with updates.

We have linked the feature request in our system to this ticket so they will be taken into consideration when is selected for development.

Note that because we prioritize enterprise customer support, it might take us some time to update this ticket.

This is the reference and summary of the relevant issue:

___


AG-4971 | [Regression] When using server-side row model with paging, page size not shown in pagination panel anymore
-- | --

**Comment by makinggoodsoftware** [comment]
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Comment by pinutz23** [comment]
AG-4971 is marked as fixed in v25.1.0, but the problem still exists.

Navigating to the last (maybe also the next?) page the first time: 
![image](https://user-images.githubusercontent.com/7524745/113700633-5dc10d00-96d7-11eb-8554-2259fe8aebac.png)

Navigating back to the first page and after that the last page again, finally shows the correct number.

**Comment by lwouis** [comment]
I can confirm that the issue is not fixed on v25.1.0. I mentioned this in a ticket on the ZenDesk as my company is a paying customer, together with another regression with the `startRow` and `endRow` parameters being `undefined` after updating from v24.1.0 to v25.1.0

**Comment by kiril-matev** [comment]
Hello @lwouis,

I responded in the support ticket you opened about the startRow and endRow parameters. In AG Grid v25 we did a major update of the SSRM adding significant new functionality covered here:
https://blog.ag-grid.com/whats-new-ag-grid-v25/

As part of these changes we introduced the concept of rowStores, allowing you to select whether the records on a particular level are retrieved all in one from the server (new default behavior, post v25), or retrieved in pages (now optional behavior, same as pre-v25) described here:
https://www.ag-grid.com/javascript-grid/server-side-model-row-stores/

This change in default loading strategy is the reason you're seeing undefined values for startRow and endRow - it's because by default v25 retrieves all the records on a specific grouping level. This is why when upgrading to v25 we highly recommend understanding the changes and modifying the codebase if you want to keep the old pre-v25 behavior:
https://blog.ag-grid.com/upgrading-to-ag-grid-v25-server-side-row-model/

@lwouis @JannikWempe:
Regarding the issue you've reported with "?" displayed instead of page size originally logged under AG-4971. This issue was fixed in v25.1. We've since tested a number of scenarios and haven't been able to reproduce this issue with v25.1.

We're keen to investigate further and resolve this in your scenario. Please provide a sample in plunker illustrating this issue allowing us to move forward. You can modify this example in our documentation to reproduce this issue:
https://www.ag-grid.com/javascript-grid/server-side-model-pagination/#example-pagination

Looking forward to your response, so we can get this issue reproduced and resolved.

Thank you for your time!

**Comment by lwouis** [comment]
@JannikWempe I added `serverSideStoreType={ServerSideStoreType.Partial}` to the `AgGrid` component, and it started sending `startRow`/`endRow` again to the backend, and the issue you described - which I could reproduce before I added `serverSideStoreType` - is now gone.

**Comment by kiril-matev** [comment]
Thanks for the update @lwouis - glad to hear the issue is now resolved!

@JannikWempe 
Please confirm if that resolves the issue on your end as well.

**Comment by w3slley** [comment]
We were also able to reproduce this issue on version 30.2.0

**Comment by ericmartinezr** [comment]
In my case, using Infinite Row Model (community version) and Angular, it was because I was calling the same function in different Grid Events causing it to sometimes fail at rendering the correct numbers. Note that sometimes with the 2 calls it still showed the correct numbers (very rare case) so it was some race condition or similar.

```ts
(gridReady)="onGridReady($event)"
(gridSizeChanged)="onGridReady($event)"
// ...
onGridReady(params) {
  params.api.updateGridOptions({ datasource: this.datasource });
}
```
By removing the latter event (gridSizeChanged) it started working correctly.

I'm using Angular 17+ and AgGrid v31.1.1.

**Comment by mford-rgare** [comment]
Its broken like this for me also. In fact its actually broken on your own web site.
https://www.ag-grid.com/javascript-data-grid/server-side-model-pagination/#example-server-side-pagination

**Comment by iamcarlo042** [comment]
As for version 31.2.0, this is still occurring.
In my case, I am on React.

I still make use of this temporary fix.
https://github.com/ag-grid/ag-grid/issues/4295#issuecomment-762007883

I call the function setLbLastRowOnPage() inside onPaginationChanged().

```
...
onPaginationChanged(params) {
        setLbLastRowOnPage(params?.api);
},
...
```

**Comment by AG-Zoheil** [comment]
Hi @iamcarlo042,

This is a regression from `31.1`. We have a bug raised for this which will be fixed in our next release: **AG-11123**.

Meanwhile please use version `31.1`. 

Kind regards,
Zoheil

**Comment by mmarkell** [comment]
I'm getting this same error on 31.1

**Comment by AG-Zoheil** [comment]
Hi @mmarkell,

Please note that this has been resolved already via the release of **AG-11123** in `31.3.1`. Please upgrade to this version to benefit form this fix.

Thank you!
