### ISSUE TITLE
copySelectedRowsToClipboard Issue with Column Grouping

### ISSUE THREAD

**Issue by W4775** [ag-grid/ag-grid#4550]
**I'm submitting a ...**
```
[X] bug report
[] feature request 
[] support request
```

**Current behavior**
Using copySelectedRowsToClipboard() and Column Groups will always copy the column group headers. The includeHeaders param only affects the column headers and not the header groups.

See example here (I added row copy and row copy with header to context menu):
https://plnkr.co/edit/YZgFdZvNGYKge1Jh

**Expected behavior**
Either add an additional param to exclude Column Group Headers or exclude the Column Group headers when includeHeader = false

* **AG Grid version:** X.X.X
25.3.0

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment]
Hello,

Thank you for coming to us with this.

Currently, API methods for copy to clipboard has only one parameter - includeHeaders, which is used to control whether column headers are copied:
**copySelectedRowsToClipboard**(includeHeaders) and **copySelectedRangeToClipboard**(includeHeaders)

This property should apply to column headers only and as you reported it currently doesn't apply to column group headers. Instead of making this property apply to all column header levels, we're planning to address this by adding a new parameter to these methods to control whether column group headers are copied.

This new parameter will provide additional flexibility in the way column headers are copied, and consistency with the Excel export API where we also use two separate properties to control whether column headers and column group headers are exported - properties skipColumnHeaders and skipColumnGroupHeaders:
https://www.ag-grid.com/javascript-grid/excel-export-api/#excelexportparams

This is why this isn't a bug as the includeHeaders property wasn't meant to apply to column group headers. We have logged a feature request to add a new property:
**AG-5501 [Clipboard] Allow copySelectedRowsToClipboard and copySelectedRangeToClipboard to allow/suppress the copying of column group header values**

This can still be picked up by our team when they're making modifications to this functional area of AG Grid. Please use the functionality currently provided by AG Grid until this is delivered at a later point.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment]
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Comment by andrey-voytenko** [comment]
Hi, do you have any information when this problem will be fixed?

**Comment by kiril-matev** [comment]
Hi @andrey-voytenko,

As I mentioned before, this isn't a problem with the way the current implementation is built. It is a new requirement and we've entered a feature request for it. 

We have no timeline for this feature request, but can still be picked up by our team when they're making modifications to this functional area of AG Grid. 

**You can get an update at any one time for this item at the product pipeline page to see which items we're targeting to include for the next release:
https://www.ag-grid.com/ag-grid-pipeline/

Also, sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thank you for following up with us!

**Comment by blakthorn666** [comment]
Hi @kiril-matev,

We also would like to get that feature. In order to stay up-to-date on the progress of this feature, I followed your advice of checking out both the ag-grid-pipeline and the ag-grid-changelog, but when I look for the issue "AG-5501", it doesn't return any results. Is "AG-5501" the correct id for this issue?

Thanks

**Comment by kiril-matev** [comment]
Hi @blakthorn666 

Thanks for reaching out.

Yes, AG-5501 is the correct ID for this issue.

**Please search the product pipeline page for this item:
https://www.ag-grid.com/ag-grid-pipeline/**

See a screenshot of this displayed below;
![image](https://user-images.githubusercontent.com/60937283/134532213-10926b2a-bac4-4d86-b790-91f8f87041fb.png)

**Comment by blakthorn666** [comment]
Hi @kiril-matev,

I still can't see the issue:

![image](https://user-images.githubusercontent.com/13457070/134539655-2624ddfe-9d79-4920-bdc9-770ec38a5204.png)

**Comment by kiril-matev** [comment]
Hi @blakthorn666 

Apologies for the fact it's not displayed on the page as you indicated - this is due to an issue which sometimes results in all items appearing in the list. Please check back later. 

I can confirm AG-5501 is an active feature request we're tracking.

**The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

**Comment by blakthorn666** [comment]
Will do. Thank you, @kiril-matev!
