### ISSUE TITLE
Horizontal scrolling only works in the content areas, not header

### ISSUE THREAD

**Issue by vny-cg** [ag-grid/ag-grid#4613]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
```

I am getting the exact same behaviour as this ticket: https://github.com/ag-grid/ag-grid/issues/2634

The issue stated to be picked up but has since been removed from the roadmap. Can we please get some more insight into this issue?

**Comment by makinggoodsoftware** [comment]
Hi,

This was fixed in v19.1, what version are you using on your end?

Thanks

**Comment by vny-cg** [comment]
I am using 24.1.0

v19.1 was released in late 2018

As you can see from comments in the previous ticket raised on this issue people were running into this behaviour into 2020. I would say that this issue is not fixed. The behaviour is present even in the examples on the ag-grid.com website.

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment]
Hello!

Thank you for bringing this up with us. 

The functionality you described wasn't part of the requirements when we built this feature. This is why we have added a feature request in our backlog to track this requirement and implement it in the future.

You can track it with this reference:
**AG-2065 [Scrolling] Allow scrolling horizontally using the trackpad/mouse wheel when over the column headers**

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by AndrewZagovora** [comment]
The issue with horizontal scroll also present in the pinned sections (left and right). The scroll is not working.
Even in your web site - https://www.ag-grid.com/javascript-data-grid/column-pinning/

**Comment by kiril-matev** [comment]
@AndrewZagovora:

The issue described above refers to trying to scroll horizontally when hovering the column headers.

Are you trying to scroll horizontally in the pinned area over the data rows, or the column headers?

**Comment by AndrewZagovora** [comment]
@kiril-matev I am trying to scroll the area. Then should I open new issue?

**Comment by kiril-matev** [comment]
@AndrewZagovora: Normally yes, you would open a separate issue for this. However, in this case there's no need to do that as I can answer this immediately - currently scrolling inside the pinned column containers is not supported.

We have a feature request for this:
**AG-3915 [Column Pinning] Allow setting maxWidth for pinned columns area (smaller than viewport) and horizontal scrolling inside the pinned column area if total pinned column width is greater than pinned area width**

**We will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!
