### ISSUE TITLE
Select Editor erroring in debug console "Processing of the expression failed"

### ISSUE THREAD

**Issue by chiprock** [ag-grid/ag-grid#5272]
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'

**Providing a Reproducible Scenario**
Steps to reproduce (current behavior)

1. Browse to https://www.ag-grid.com/angular-data-grid/provided-cell-editors/ (make sure debug console open)
2. Access the ag-grid column labeled "Select Editor".  It should be a drop down with multiple colors.
3. Notice when when you click the drop down you receive the below errors in console for each console.

--- Error below this ---
Exception = ReferenceError: Red is not defined
ag-grid-community.cjs.min.js:348 Processing of the expression failed
ag-grid-community.cjs.min.js:348 Expression = Green
--- error above this ---

**Expected behavior**
No errors is expected.

**Please tell us about your environment:**
ag-grid per the ag-grid.com website.  

* **AG Grid version:** X.X.X
version v27.3.0

* **Browser:**
Using chrome 97.0.4692.99

Issues seems to be simply a nusiance and I cannot find any problem it causes with the current implementation I am running on a local project.

**Comment by chiprock** [comment]
<img width="643" alt="cgl38CI7Ud" src="https://user-images.githubusercontent.com/8430591/173383275-69eb1a4c-d148-473f-973a-e97eaadc2ec6.png">

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by kiril-matev** [comment]
Hello @chiprock!

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a regression from v27.1.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-6847 [Regression] When starting an edit with agSelectCellEditor the valueFormatter is not called and console warnings are displayed**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by makinggoodsoftware** [comment]
Hi,

In order to help us keep our issues queue clear, we are going to close this issue

The official way to check the status for an issue raised here is to check its AG-xxxx ID against our pipeline and changelog

…the pipeline (if not yet developed)

https://www.ag-grid.com/ag-grid-pipeline/

... or the changelog, (if the issue has been resolved)

https://www.ag-grid.com/ag-grid-changelog/

We keep issues raised in the pipeline through github open for a while so that the community can add some feedback to them, and close them when there is no activity for a while.

If you want to add further feedback to a closed ticket with this comment, we would recommend opening a new ticket as we don’t monitor closed issues.

**Comment by sachinjijojacob** [comment]
This issue is not resolved on react .agrid version 27.3.0 .ag grid is full of issues. facing issue after selection of the dropdown value is showing up in grid but not in the data

**Comment by StephenCooper** [comment]
Is this producing the same error as above? If not please create a new issue with an example showing the error so that we can then investigate.

**Comment by sachinjijojacob** [comment]
I am able to select the dropdown value in line dropdown for ag ggrid. value can be seen in the grid. but data is actually not getting updated

**Comment by sachinjijojacob** [comment]
https://github.com/ag-grid/ag-grid/issues/5622
