### ISSUE TITLE
Cant Use Grouping Drag and Drop feature on Touch Devices

### ISSUE THREAD

**Issue by FIELDPOINT** [ag-grid/ag-grid#5341]
**I'm submitting a bug report**

Cant Use Grouping Drag and Drop feature on Touch Devices. You can drag the column header up to the Grouping Panel but can drop it making Grouping unusable on Mobile devices. This is a huge problem.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
-[ A plunker](https://plnkr.co/edit/?open=app%2Fapp.component.ts&preview)

**Expected behavior**
Should be able to drop the header into the Grouping Panel to initiate grouping.

**Current behavior**
Cant Use Grouping Drag and Drop feature on Touch Devices. You can drag the column header up to the Grouping Panel but can drop it making Grouping unusable on Mobile devices. This is a huge problem.

**Please tell us about your environment:**
iPad Chrome/Safari
Galaxy s21 Chrome

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by shaharshavitexp** [comment]
+1 - grouping rows by column is not working on mobile.

When I drag & drop column into the grouping line - An error is raised - "Type Error: The provided value is non-finite".
It happens also on desktop simulation of phone (via chrome dev tools).

**Comment by kiril-matev** [comment]
Hello @FIELDPOINT!

Thank you for reporting this - much appreciated!

As you're using AG Grid Enterprise features (row grouping) you are entitled to use our support portal. Please submit any issues there to get a quicker response.

Based on your description we've now reproduced this issue as a regression.

We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-7005 [Regression] When using a touch device, dragging a column header into the row group panel throws a console exception**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can see the next release date on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

**Comment by seanlandsman** [comment]
Hi,

Version 28.1.0 have AG-Grid has been released, which includes a fix for this issue.

Thank you for reporting this.

**Comment by MicheleLucini-infobit** [comment]
This issue is still present.
Step to reproduce (with chrome latest version):
1. Go to https://www.ag-grid.com/example/
2. Open the console with f12, "Toggle device toolbar" and select something with touch controls.
3. Try to group a column by drag and drop.
