### ISSUE TITLE
Tooltip is not working in ag-chart of version 8.0.0

### ISSUE THREAD

**Issue by DivakarSS** [ag-grid/ag-grid#6835]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
* Project migration from Vue2 to Vue3. and ag-grid version 29.x.x to 30.0.0  and ag-charts versions 4.x.x to 8.0.0.

**Current behavior**
In charts tooltip is not working in ag-charts version 8.0.0.
I am attaching the screenshot of version 8.0.0 for reference.
![MicrosoftTeams-image (2)](https://github.com/ag-grid/ag-grid/assets/69146417/d136e74c-b492-46d7-ad24-b02ab3a3d850)

**Expected behavior**
The tooltip will work if we hover nearer to the point.
I am attaching the screenshot of version 29.1.0 for reference.
![MicrosoftTeams-image (1)](https://github.com/ag-grid/ag-grid/assets/69146417/b66ff629-1aed-4446-b6ac-4773e0d77d37)

 

**Please tell us about your environment:**
O.S: Windows 10
IDE: VS Code
Package Manager: npm
* **AG Grid version:** 30.0.0
* **Browser:** 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36'
* Vue: 3.2.13
* ag-grid-vue3: 30.0.0
* ag-charts-vue3: 8.0.0
* ag-charts-community: 8.0.0
* TypeScript: 4.5.5

**Comment by AG-DavidG** [comment]
Hi @DivakarSS 

Thanks for submitting this as a bug.
We cannot reproduce this on our end given the information provided. 

Please can you modify a plunker example from our website, https://ag-grid.com/javascript-charts/scatter-series/#scatter-plot, and send us the link.
Alternatively we would need a live example or the entire code to be able to troubleshoot further.

Thanks

David

**Comment by DivakarSS** [comment]
Hi @AG-DavidG 

Actually tooltip is not working in Web Components only. It is working properly in normal local environment. I share the Github repo link for your reference. 
[https://github.com/DivakarSS/Ag-Charts/tree/main](url) 
In this project, I converted my component into Web Component which is available in dist folder.  Run the demo.html file in dist folder to see the Web Component output. You can also able to see the normal component by running the server cmd.

I am attaching the recording of normal component for reference.
https://github.com/ag-grid/ag-grid/assets/69146417/33668f23-bad3-48d2-8e4c-88e6adcb3467

I am attaching the recording of Web Component for reference.
https://github.com/ag-grid/ag-grid/assets/69146417/979cb952-cda1-4bbe-a90a-8d3ae360290b

Thanks,
Divakar.

**Comment by DivakarSS** [comment]
Hi @AG-DavidG ,

You can able to reproduce this issue by running "build-wc": "vue-cli-service build --mode production --modern --target lib --inline-vue --name ag-charts ./src/index.ts" this cmd in package.json file. We are generating the Web Component as per the Vue 3 documentation only.

Note:-
Before run the above cmd you need to take a copy of demo.html file in dist foled. Because that cmd will override all the files in dist folder. After the build is finish you need to replace that backup demo.html file with current demo.html file in dist folder.

Thanks,
Divakar

**Comment by AG-DavidG** [comment]
Hi @DivakarSS 

We have tested this using our own examples without any issues. 

While I can see that there is an issue with the web component in your project, it is not clear that the problem is with the AG Chart library. We do not debug entire projects and therefore cannot register this as a bug.

I would suggest that you remove everything from the project except one default chart to see if that works. You can then add the other chart settings, components and libraries to clarify where the problem is occuring.

Thanks

**Comment by DivakarSS** [comment]
Hi @AG-DavidG ,

Check this repo [https://github.com/DivakarSS/Ag-Charts](https://github.com/DivakarSS/Ag-Charts). This repo contains the example of scatter plot chart which is given in docs and I added the required libraries only.  

Here also the tooltip is not working in Web Component. You can follow the same step which is mentioned in above conversation to run or view the Web Component output.

Thanks,
Divakar

**Comment by AG-DavidG** [comment]
Hi @DivakarSS 

Thanks for this. 

We have investigated further and have identified the issue as specific to Web Components that are in a shadow DOM. 
This scenario is not currently supported by AG-Charts.

If have an AG Grid Enterprise license or are evaluating AG Grid Enterprise please submit a support ticket at https://ag-grid.zendesk.com/. This will enable us to record your interest as a feature request in our backlog.

We will soon close this GitHub issue because we will not update it if this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, you can look on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks

**Comment by yashwanth2714** [comment]
@AG-DavidG Is this issue fixed in the latest release ag-charts version 8.0.5

**Comment by yashwanth2714** [comment]
@AG-DavidG This is still not working in the latest version 9.0.2. Can you please tell me when this will be resolved?

**Comment by AG-DavidG** [comment]
Hi @yashwanth2714 
I'm afraid that currently we can't commit to a specific timeline for addressing this issue.

As part of our work for a specific release, we pick an area of AG-Charts to focus on and we implement new functionality and address issues related to that area. If this issue falls within the area we'll be working on, there's a chance it will get picked up. 

This is how it can potentially be implemented and included in a future release without further notice.

For now, please check our pipeline once a month for any updates on this: https://charts.ag-grid.com/pipeline/

We believe it's important to be transparent with you about this and we're sorry we cannot commit to implementing this behavior in the short term. 

Please treat this as a known issue until this gets resolved at a later point.
