### ISSUE TITLE
[Bug] Cellrenderer data is always one step behind if rowData is update and getRowId is provided

### ISSUE THREAD

**Issue by ahmadi3d** [ag-grid/ag-grid#7123]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Providing a Reproducible Scenario**
1- Update a rowData in an interval.
2- Provide a getRowId
3- Have a cellRenderer column
4- the bug happens! the data in cellRenderer is always one step behind.
Here is a link showing this: 
https://codesandbox.io/s/cellrenderer-getrowid-bug-79jk5c

**Current behavior**
If you update a rowData and provide a getRowId, the cellRenderer columns gets updated with the previous/old data

**Expected behavior**
I expect the moment the data update in a row is detected and getRowId is provided, cellRenderer updates
with the latest data.

Please tell us about your environment:
* **OS:** Windows
* **Browser:** Google Chrome
* **AG Grid version:** 30.0.2
* **Language:** [ReactJS]

**Comment by AG-Zoheil** [comment]
Hello @ahmadi3d, 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-9507**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by XijueYZ** [comment]
This issue recurred in version 31.1.1, and updating to 32.0.0 did not fix it. Please confirm again. @AG-Zoheil

**Comment by AG-Zoheil** [comment]
Hi @XijueYZ,

I've checked `v32.0.2` with the below test case and it works for me. If you can fork the example and provide a reproducible scenario of it not working we can have a look: https://plnkr.co/edit/FOUs8ZqqUu3Et1fg?open=index.jsx

Thank you!

**Comment by XijueYZ** [comment]
@AG-Zoheil When I wrap the definition of columns with useMemo and then use getRowId, this issue occurs when updating the data. Is this expected?
https://plnkr.co/edit/JylPLIoAJCyWfDTp?open=index.jsx
