### ISSUE TITLE
Tooltip with interaction does not always disapear 

### ISSUE THREAD

**Issue by mikymike95** [ag-grid/ag-grid#7137]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**

1. Activate tooltipInteraction
2. Create a custom tooltip component
3. Interact with the tooltip (click , submit ...) and move your mouse to another cell with interactive tooltip then restrart

**Current behavior**

After activating new **tooltipInteraction** option to make cell tooltip interactive, sometimes it's ipossible to make it disapear after click on it. 
PS: You can reproduce this issue with the demo [here](https://www.ag-grid.com/angular-data-grid/component-tooltip/)
or try the [plunker](https://plnkr.co/edit/?open=app%2Fapp.component.ts&preview)
![image](https://github.com/ag-grid/ag-grid/assets/25712466/6642a85a-afb2-41fd-9e25-507d4dbd2044)

![image](https://github.com/ag-grid/ag-grid/assets/25712466/a726b1b8-20ae-4226-9591-0229d9d51d54)

https://github.com/ag-grid/ag-grid/assets/25712466/fc53ea22-1472-4275-b843-3c2295dca852

**Expected behavior**
After interact with a tooltip it should disapear after interaction

* **AG Grid version:** 30.2.0

* **Browser:**
Chrome

* **Language:** [TypeScript 4.9.5 | Angular 16]

**Comment by AG-Zoheil** [comment]
Hello @mikymike95,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: AG-9548

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by marinhov** [comment]
Hi @AG-Zoheil,

the problem is still present in the current demo example: 
![image](https://github.com/ag-grid/ag-grid/assets/65512343/0afa630d-f52b-466b-882e-10c17cb7e55c)

Do you have some news ?
Can we open a ticket in zendesk support to prioritize this issue ? 

Thanks

**Comment by AG-Zoheil** [comment]
Hi @marinhov,

Thank you. We have reopened the corresponding item in our backlog (AG-9548).

Yes, please note we would always recommend our enterprise users to get in touch via Zendesk as opposed to GitHub as it will be the most efficient way to get an answer from our support team.

Kind regards,
Zoheil
