### ISSUE TITLE
SSRM, missing `storeRefreshed` event

### ISSUE THREAD

**Issue by maximshipko** [ag-grid/ag-grid#7353]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Precondition**

- A grid with SSRM, 
- The row counter is less than `cacheBlockSize` (so the whole dataset is fetched by datasource in a single request)
- The grid is refreshed without a purge option

```typescript
api.refreshServerSide({ purge: false })
```
- On the server, the **last rows** from the dataset are getting removed, so after the refresh row counter goes down.

**Current behavior**

AG Grid doesn't trigger `storeRefreshed` event if rowCount "goes down" after refresh.

**Expected behavior**

The `storeRefreshed` event should be triggered after refresh without the purge option.

**Providing a Reproducible Scenario**
Planker [example](https://plnkr.co/edit/gizBd6Bc7CaSTfxF?open=index.tsx)

(This example is made based on existing from the [documentation](https://www.ag-grid.com/react-data-grid/server-side-model-updating-refresh/#simple-example))

To observe the issue, open the console, and click "Refresh Rows" several times. Observe in the console log, that there is no single output from the event handler.

**AG Grid version:** X.X.X
30.2.0, 
31.0.0

**Comment by AndrewGlazier** [comment]
Hello,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
AG-10157 - [SSRM] When reducing number of rows after refresh, storeRefreshed event never fires

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can get an update on the status of this item on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-10157) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Comment by PiotrPieprzyk** [comment]
@AndrewGlazier I cannot find the ticket that you have mentioned, and the issue still persist

**Comment by mykytagrusha** [comment]
@AndrewGlazier, could you confirm whether the ticket you provided is correct? Couldn't I find it in the backlog or pipeline?
