### ISSUE TITLE
setGridOptions('columnDefs', [...] ) has trouble inferring generic type

### ISSUE THREAD

**Issue by KrazyTako** [ag-grid/ag-grid#7503]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

In the previous version of AG Grid (30.x using agGrid.api.setColumnDefs), we were able to call a generic function to build Grid Columns and their generic types would be implicitly resolved based on the AG Grid's initial generic <TData> type. This no longer works with the API changes introduced in AG Grid version 31.
```
interface MyType {
    name: string;
}

agGrid: AgGridAngular<MyType>

setUp() {
    this.agGrid.api.setGridOption('columnDefs', [
        buildColumn({                               // generic type inference no longer works. Gets set to "unknown"
            valueGetter: params => params.data.name // "name" does not exist on type "unknown"
        })                                         
        buildColumn<MyType>({                       // explicit type is now required
            valueGetter: params => params.data.name // ok now
        }) 
    ])
}

buildColumn<TData>(overrides: ColDef<TData>): ColDef<TData> { 
    return {
        <projectDefaultProperties>
        ...overrides
    }
}
```

**Expected behavior**

In version 30.x we were able to do this:
```
interface MyType {
    name: string;
}

agGrid: AgGridAngular<MyType>

setUp() {
    this.agGrid.api.setColumnDefs([
        buildColumn({                               // Correctly calls with implicit generic type
            valueGetter: params => params.data.name // ok
        })                                         
    ])
}

buildColumn<TData>(overrides: ColDef<TData>): ColDef<TData> { 
    return {
        <projectDefaultProperties>
        ...overrides
    }
}
```

**Additional findings**
I noticed that the declaration of `setGridOption` could probably be narrowed a little better:
```
From:
setGridOption<Key extends keyof GridOptions & ManagedGridOptionKey>(key: Key, value: GridOptions[Key]): void;

To:
setGridOption<Key extends keyof GridOptions & ManagedGridOptionKey>(key: Key, value: GridOptions<TData>[Key]): void;
```
That seems to get us a little closer, but for some reason we'd need to be explicit about the generic keyof now:
```
// requires explicit <'columnDefs'>
this.agGrid.api.setGridOption<'columnDefs'>('columnDefs', [
    buildColumn({                               // correctly inferred now!
        valueGetter: params => params.data.name // ok
    })                                         
])
```

I'm not sure what TypeScript magic would be needed here to get it to work as before, and without the need to do `setGridOption<'columnDefs'>('columnDefs', [...])`. But it would be really nice to support this the same way that it worked in version 30.x. 

Thank you.

**Please tell us about your environment:**

* **AG Grid version:** 31.0.2

* **Language:** TypeScript 5.1.6

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-10481**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by StephenCooper** [comment]
Hi @KrazyTako,

Thanks for highlighting this. You were close with your suggestion, just missing one extra TData. We will get this fixed for the next release and also make the same change for the `updateGridOptions` and `getGridOption` methods.

**Comment by KrazyTako** [comment]
I appreciate it @StephenCooper. Thanks for looking into this.

**Comment by david-rodriguez-rev** [comment]
Hi @StephenCooper I just upgraded my project to the latest AG Grid and it seems this issue is still present. Is there anything that can be done about this?

**Comment by AG-Zoheil** [comment]
Hi @david-rodriguez-rev,

This was completed in `31.1`. If you are running our latest version and still experiencing issues can you please provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

Kind regards,
Zoheil
