### ISSUE TITLE
[React 30.1.0] Data collapsed into first column when rendering a large amount of columns and the data was updated frequently

### ISSUE THREAD

**Issue by tiandengpan** [ag-grid/ag-grid#7516]
```
[X] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Current behaviour**.
Data collapsed into first column when rendering a large amount of columns and the data was updated frequently
![chrome-capture-2024-1-31 (1)](https://github.com/ag-grid/ag-grid/assets/39333511/38ee1d7d-b8f2-4515-a512-26d6ca0219d6)

**Expected behavior**
The data was rendered correctly

**Environment**
Windows 10, vscode v1.84.1, npm v10.1.0, node 20.9.0

AG Grid version: "ag-grid-react": "^30.2.1",
Browser: Chrome
Language: es6, target "es2020"

**Comment by tiandengpan** [comment]
Hi dear team,
A throttle will work, but maybe you have a better idea to fix this issue.

**Comment by Matvey1308** [comment]
Hi @StephenCooper , I have the same issue on 31.0.3, still reproducible

**Comment by StephenCooper** [comment]
Could you please provide a reproduction that shows this still happening with the latest version please?

Will make it a lot easier to debug if you can do that.

**Comment by Matvey1308** [comment]
@StephenCooper  thank you for fast response. 

Video is attached to the comment. 

Pre-requisites: 
- Platform: Macos 13.1
- Browser: Chrome 121.0.6167.160
- Language: es6, react
- Version: "ag-grid-community": "31.0.3",

Code:  onGridReady -> api.sizeColumnsToFit();

https://github.com/ag-grid/ag-grid/assets/15235813/1cc78fc7-3104-4217-9973-467746fd2bb9

**Comment by StephenCooper** [comment]
Thanks for the video but we would need a code sample too. Can be a git repo if that's easier. Or if possible to reproduce using one of our documentation examples that would be good too. 

Are you using initialState?

**Comment by tiandengpan** [comment]
@StephenCooper 
Sorry for the late response. We were in the Chinese new year vacation.
I invited you into the sandbox demo project.
https://codesandbox.io/p/sandbox/ag-grid-packages-forked-n87rgv?file=%2Fsrc%2Findex.js%3A18%2C6
Please check whether you can get access to it.

**Comment by StephenCooper** [comment]
Hi @tiandengpan,

Are you using `getRowId`?  https://ag-grid.com/react-data-grid/row-ids/

From the reproduction you provided I can see that if you provide this then the grid is able to work a lot faster. This is because it can then work with transactions and is able to identify that only one row has been updated and not need to re-render all the rows.

**Comment by tiandengpan** [comment]
> Hi @tiandengpan,
> 
> Are you using `getRowId`? https://ag-grid.com/react-data-grid/row-ids/
> 
> From the reproduction you provided I can see that if you provide this then the grid is able to work a lot faster. This is because it can then work with transactions and is able to identify that only one row has been updated and not need to re-render all the rows.

Many thanks @StephenCooper.
Does this solve your problem @Matvey1308?

**Comment by AG-Zoheil** [comment]
As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

**Comment by trypton** [comment]
We had same issue after migrating to v31 and in our case removing `width` from col definitions solved it.

**Comment by Sohamsanghavi** [comment]
We are still facing the same issue after migrating to v32.0

**Comment by weystorm** [comment]
We were facing the same issue, but v32.2.0 seems to have fixed it without any modification in the code itself.

We have finally migrated from v30.2.1 as this was a regression for us. Note: we could still see this problem in v32.0.0.
