### ISSUE TITLE
[React] - cellRenderer on filterParams flicker/re-render on each checkbox toggle

### ISSUE THREAD

**Issue by ben-walkme** [ag-grid/ag-grid#7698]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Detailed steps to reproduce**
1. Go into [ag-grid filter-set-list](https://www.ag-grid.com/react-data-grid/filter-set-filter-list/#cell-renderer) , choose React 
2. Copy the example cellRenderer component from the snippet countryCellRenderer 
3. Simplify it, by only returning the value 
```
import React, { useEffect, useState } from 'react';

export default (props) => {
  const [value, setValue] = useState();

  useEffect(() => {
    if (!props.value) {
      setValue(props.isFilterRenderer ? '(Blanks)' : props.value);
    } else {
      setValue(props.value);
    }
  }, []);

  return <div>{value}</div>;
};
```
4. Provide the TestCellRenderer to the filterParams in columnDefs or defaultColumnDefs:
```
     filterParams: {
          cellRenderer: TestCellRenderer
      }
```
5. Toggle the checkbox in the filter section and observe the flickering

**Additional information**
* Resolve with native javascript
* The issue are also occurring in ag-grid docs for React, toggle the checkbox in counteryCellRenderer example.  i've also attached a short video of it
 * Same behavior with React.memo 
 * Same behavior with React.forwardRef, React.useImperativeHandle and refresh method
 ```
 const TestCellRenderer = React.forwardRef((props, ref) => {
  const [value, setValue] = React.useState(props.value);

  React.useEffect(() => {
    setValue(props.value);
  }, []);

  React.useImperativeHandle(ref, () => {
    return {
      refresh: (params) => {
        setValue(params.value);
        return true;
      },
    };
  });

  return <div>{value}</div>;
});
 ```
 
**Current behaviour:**
cellRenderer on filterParams flicker/re-render on each checkbox toggle

**Expected behaviour:**
Resolve with React

**Please tell us about your environment:**
MacOs ventura v13.6
Visual Studio Code v1.86.2 ( Universal )
React version v17.0.2
Node v18.16.0 
Npm v9.5.1

* **AG Grid version:** 28.1.0

* **Browser:** Chrome, Version 12

2.0.6261.112 (Official Build) (arm64)

* **Language:** all

**Short recording**

https://github.com/ag-grid/ag-grid/assets/144128249/750ba18d-121b-4394-a8f7-314e0ecbaa97

Ag-grid docs

https://github.com/ag-grid/ag-grid/assets/144128249/fb2bdfce-f144-4abb-aca1-acbf037ba228

**Comment by AG-Zoheil** [comment]
Hello @ben-walkme,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-11033**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by bogdanS-e** [comment]
I have the same problem and it's not fixed.
If I have `defaultColDef` (even if it's an empty object) the options still flick.

I use server-side data model

if I remove `defaultColDef` everything works fine


I use AG ag-grid-react v33. latest Chrome browser

**Comment by sabahang** [comment]
@bogdanS-e would you be able to send us a live plnkr that shows the issue is not resolved?

**Comment by bogdanS-e** [comment]
@sabahang 
there you go https://codesandbox.io/p/sandbox/column-moving-simple-forked-7s3qwg?file=%2Fsrc%2Findex.tsx%3A70%2C11
I have a similar component structure in my project. But here I use a mock API service (not my real API)

Notice if you remove line 75 `defaultColDef={{}}` it won't flick
If you remove `setIsLoading` in `ComponentRenderer` it will fix the problem too. But it's unacceptable for my project because the loading state comes from parents/global store, etc...

**Comment by bogdanS-e** [comment]
https://github.com/user-attachments/assets/11546fd2-fbc4-42b4-9a0f-037c03c1748d


there is the recording how it works for me in the CodeSandbox
sorry for the bad quality. But you see how it flick
 "ag-grid-react": "33.0.3",
 "ag-grid-community": "33.0.3",
 "ag-grid-enterprise": "33.0.3"

**Comment by sabahang** [comment]
@bogdanS-e this is likely because you are not using Hooks. Please see here:
https://ag-grid.com/react-data-grid/react-hooks/#object-properties

if this doesn't resolve the issue happy to look into it further

**Comment by bogdanS-e** [comment]
@sabahang you are right! Thanks! now it works fine!
