### ISSUE TITLE
SSRM pagination: Getting question mark "?"  in the pagination 

### ISSUE THREAD

**Issue by madhavawasthi6430** [ag-grid/ag-grid#7798]
Here is my code 

const MyServerSideDataSource = () => {
    const getRows = async (params) => {
      const startRow = params.request.startRow;
      const endRow = params.request.endRow;
      const pageSize = endRow - startRow;
      const pageNumber = Math.floor(startRow / pageSize) + 1;
      const { filterModel, sortModel } = params.request;
      setSortColumn(sortModel);
      const sort = localStorageSettings?.sortModel || [];
      params.api.hideOverlay();
      try {
        const data = await apiService.invoiceListAPI(
          10,
          pageNumber,
          '',
          filterModel,
          !isEmpty(sortModel) ? sortModel : sort
        );
        if (data?.data?.data?.length > 0) {
          console.log("abcabcabc4231", data?.data?.data, data?.data?.page_details.no_of_records)
          params.success({
            rowData: data?.data?.data,
            rowCount: data?.data?.page_details.no_of_records
          });
        } else {
          onBtShowNoRows();
          params.success({
            rowData: [],
            rowCount: 0
          });
        }
      } catch (error) {
        params.fail();
      }
    };

    return {
      getRows: getRows
    };
  };
  
  
  const gridOptions = {
    rowModelType: 'serverSide',
    suppressFocusAfterRefresh: true,
    serverSideStoreType: 'partial',
    cacheBlockSize: 10,
    paginationPageSize: 10,
    serverSideDatasource: MyServerSideDataSource(),
    enableCellTextSelection: true,
    resizable: true,
    onSelectionChanged: onSelectionChanged,
    rowSelection: 'multiple',
    suppressRowClickSelection: true,
    headerCheckboxSelectionCurrentPageOnly: true,
    pagination: true,
    sideBar: {
      toolPanels: [
        {
          id: 'columns',
          labelDefault: 'Columns',
          labelKey: 'columns',
          iconKey: 'columns',
          toolPanel: 'agColumnsToolPanel'
        }
      ]
    },
    suppressAggFuncInHeader: true
  };
  
  
  
![image](https://github.com/ag-grid/ag-grid/assets/41377657/3a78e0a9-36bd-4167-9330-b9e5039f9fa9)

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: AG-11123

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by iamcarlo042** [comment]
As for version 31.2.0, this is still occurring.
In my case, I am on React.

I still make use of this temporary fix ⬇️ 
https://github.com/ag-grid/ag-grid/issues/4295#issuecomment-762007883

I call the function setLbLastRowOnPage() inside onPaginationChanged().

```
...
onPaginationChanged(params) {
        setLbLastRowOnPage(params?.api);
},
...
```

Maybe this idea will help someone. Cheers!
