### ISSUE TITLE
Possible memory leaks of applyTransactionAsync

### ISSUE THREAD

**Issue by nikolastojanovictt** [ag-grid/ag-grid#7854]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
- In real case scenario, data received from websocket connection is being added to table by applyTransactionAsync method. Heap snapshot keeps rising after updates. Garbage collection doesn't have effect.
Issue is reproducible in React version of first plunker example https://ag-grid.com/react-data-grid/data-update-high-frequency/, but not in Javascript version https://ag-grid.com/javascript-data-grid/data-update-high-frequency/. You can reproduce the issue by clicking Async Update button and taking several heap snapshots (5 - 10 heap snapshots)
- Example with automatic updates in 250ms period is available in my Plunker: https://plnkr.co/edit/l3NUDgcstGqOCpMK?open=index.tsx

**Current behavior**
Heap snapshots are showing constant rise in memory usage.

**Expected behavior**
Proper memory cleanup.

**Please tell us about your environment:**
Windows 11, VS code 1.88.0

* **AG Grid version:** 31.1.1

* **Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

* **Language:** TypeScript 5.3.2

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-7519**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by nikolastojanovictt** [comment]
In addition to previous repro steps, I tried to create several workarounds:
1. using regular applyTransaction
2. trying to create rowData state
3. trying to update it by using api.setGridOption('rowData', data)

All workarounds have created same memory issues, so conclusion is that it is a general problem with rowData memoization.

**Comment by nikolastojanovictt** [comment]
Hi, I saw:
AG-7519 [React] Investigate potential memory leak in React after calling setRowData
marked "DONE" in changelog of v31.3.1. However, issue is still reproducible.

**Comment by evelyn361745** [comment]
遇到同样的问题，通过applyTransactionAsync移除数据的时候卡死，cpu打满
<img width="1654" alt="image" src="https://github.com/user-attachments/assets/0546dd18-e46c-4217-b8eb-7697613e8038">
