### ISSUE TITLE
Tooltips occasionally get stuck open forever

### ISSUE THREAD

**Issue by cseickel** [ag-grid/ag-grid#7946]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => see 'Providing a Reproducible Scenario'
[ ] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[x] support request => see 'Requesting Community Support'
```

**Current behavior**
A very small percentage of the time, an interactive tooltip from a grid cell will not close. This is maybe 1 in a hundred or one in a thousand, but we use tooltips extensively so this is an every day occurrence.

We did not have this issue before switching to interactive tooltips. We use interactive just so that the user can move their mouse over the tooltip and stop it from closing or having the focus move to another cell. The main reason we need this is that data updates every few seconds and the rows will move around due to sorts and filters.

Unfortunately, I cannot recreate this issue on demand and I've been unable to find any discernible pattern. As a workaround, I've added a click event to the custom tooltip component that will call the `hideTooltipCallback` and that does work. This enables the user to correct the situation without reloading the page.

Do you have any idea what can cause this or offer any advice on how to debug the issue?

**Expected behavior**
The tooltip closes when the mouse focus goes elsewhere.

**Please tell us about your environment:**
AG GRID 31.1.1
React 18.2.0
Electron and Chrome browsers
React Query 4 & 5
TRPC v10 and v11 beta

* **AG Grid version:**31.1.1

* **Browser:** 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) RVADesktop/3.0.0 Chrome/122.0.6261.156 Electron/29.3.1 Safari/537.36'

* **Language:** Typescript 5.0.2

**Config**

The relevant options applied are:

```ts
gridOptions={{
    tooltipShowDelay: 0
}}
tooltipHideDelay={600_000}
tooltipInteraction={true}
```

Thank you for any assistance you can provide.

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-9548**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

See whether this item will be in the next release by checking the NEXT RELEASE checkbox on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by AG-Zoheil** [comment]
Sure,

1. Open https://plnkr.co/edit/McKySQBcIHVro13k?open=main.js
2. Hover over a cell in the “Athlete” column
3. Interact with the tooltip by pressing “Submit”
4. Repeat above steps a few times and keep hovering new tooltip after clicking “Submit”

**Comment by cseickel** [comment]
Do you consider this issue fixed? We have upgraded to 32.0.02 and we are still getting the issue. It may be less frequent now though.

**Comment by AG-Zoheil** [comment]
Hi @cseickel,

We are unable to reproduce it any longer. If you have a viable reproduction example we can have another look.

**Comment by cseickel** [comment]
Hi @AG-Zoheil, thanks for the response. Unfortunately we have been unable to recreate it on demand. I will open a new issue if that changes.
