### ISSUE TITLE
AGGrid does not load theme css on first time load, On refresh theme is applied

### ISSUE THREAD

**Issue by panther008** [ag-grid/ag-grid#8325]
**I'm submitting a ...**  
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- Ag Grid theme ag-theme-quartz-dark, does not apply on first load, we have to refresh every time to load the theme

**Current behavior**
- Ag Grid theme ag-theme-quartz-dark, does not apply on first load, we have to refresh every time to load the theme

**Expected behavior**
- Ag Grid theme ag-theme-quartz-dark, should be populated on first load

**Please tell us about your environment:**
Windows 11, VS code, "ag-grid-react": "^31.0.3", 

* **AG Grid version:** 31.0.3

* **Browser:**
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by umardev1** [comment]
facing this same issue, css not loading on initial render

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by panther008** [comment]
@AG-Zoheil it occurs randomly ,

**Comment by CodrinSocol** [comment]
@AG-Zoheil I am encountering the same issue. We have a Next.js project set up and on initial render, the table does not load any CSS at all. After refreshing the page the first time, the CSS then loads up normally every time afterwards.

First Render:
![image](https://github.com/user-attachments/assets/d6498705-870b-4437-b1c2-2d6d8de0ab57)

Successive Renders:
![image](https://github.com/user-attachments/assets/bc59f8a5-4cce-43f4-95ca-5668093dbc3f)


I tried manually importing the theme, but to no success. I tried importing it like this:
`import "ag-grid-community/styles/ag-theme-quartz.css"`

This issue happens both in development and production builds.

**Comment by everettglovier** [comment]
I'm also having his problem using NextJS 14. It loads almost randomly.

**Comment by BernieSumption** [comment]
It looks like two slightly different issues are happening here.

@panther008 your screenshot shows a grid with base styles applied but no theme. This happens with `ag-grid.css` is loaded but either a) `ag-theme-themename.css` is not loaded or b) there is no `class="ag-theme-themename"` applied to the wrapper div. This is probably an issue with your application loading styles. Next time the issue happens, use the developer tools to inspect the page and find out which of the above issues are happening.

@CodrinSocol I suspect what's happening in your case is that the grid is rendered before the styles have loaded. In v31 and earlier the grid measured its row height once on startup, and if the styles loaded after this then the measured row height would be off. We fixed this in v32 so upgrading should resolve the issue. If you can't upgrade yet, deferring the grid initialisation until after your styles have loaded will work too.

**Comment by CodrinSocol** [comment]
@BernieSumption I have tried bumping up the version to v32 and I am still encountering this issue.

**Comment by AG-Zoheil** [comment]
Hi @CodrinSocol,

Thanks for getting back.

Can you please send us a live plunker sample which shows the issue. We need to be able to reproduce this to look into it further. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by djefx** [comment]
Hi AG-Zoheil, open this URL in incognito: https://www.ag-grid.com/example/

**Comment by djefx** [comment]
something like this: https://www.ag-grid.com/example/?theme=ag-theme-quartz-dark/

**Comment by BernieSumption** [comment]
@djefx thanks for bringing this to our attention, it looks like the links are broken on our theme page, the correct URL is supposed to be https://www.ag-grid.com/example/?theme=ag-theme-quartz-dark (no slash)

But to be clear, this is a bug with our theme page, not the grid product. They are a little bit related, in so far as this is what the grid looks like when base styles (ag-grid.css) are applied, but no theme is applied:

<img width="792" alt="image" src="https://github.com/user-attachments/assets/89a4ace5-fa8b-4f30-9077-90f9ef8500e1">

So if your grid looks like the above image, it's likely a bug in your application caused by:

1. not loading ag-theme-quartz.css
2. or not applying `class="ag-theme-quartz"` to the parent element of the grid.

If anyone is still experiencing issues then we'll need a reproduction in Plunker in order to look into it further.

**Comment by CodrinSocol** [comment]
@BernieSumption I checked the URL provided by you (https://www.ag-grid.com/example/?theme=ag-theme-quartz-dark). The issue I encountered happens on the URL you provided, on your website. When loading the page for the first time, the CSS theme does not load.

I use Chrome v129, if that is any help.

**Comment by BernieSumption** [comment]
@CodrinSocol interesting, I'm not seeing it. Can you check a few things for me please?

1. Confirm your OS version and exact Chrome version
2. Send a screenshot of your whole browser window including address bar demonstrating the issue
3. Confirm whether you can reliably trigger the issue every time, and if so the steps to trigger it
4. Check the developer console for errors, and the network tab for 404s
5. Disable all extensions and see if you can reproduce the issue in an incognito window

Thanks

Bernie

**Comment by AG-Zoheil** [comment]
As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

**Comment by khoait** [comment]
I'm experiencing the same. Looking in to the DOM, I found there is a `<style>` node injected after the ag global styles (at the top of `<head>`) which overwrites theme styles. Manually deleting the `<style>` node, I can see the theme styles are applied correctly. It only happens at the first render/open the URL, doesn't happen after refreshing the browser tab.

<img width="1628" alt="Image" src="https://github.com/user-attachments/assets/a4878f7f-4d79-40da-9f4b-631b59267598" />

I'm using v33. It's happening for both legacy theme and the new theming API.

**Comment by CodrinSocol** [comment]
> I'm experiencing the same. Looking in to the DOM, I found there is a `<style>` node injected after the ag global styles (at the top of `<head>`) which overwrites theme styles. Manually deleting the `<style>` node, I can see the theme styles are applied correctly. It only happens at the first render/open the URL, doesn't happen after refreshing the browser tab.
> 
> <img alt="Image" width="1628" src="https://private-user-images.githubusercontent.com/8686497/414695123-a4878f7f-4d79-40da-9f4b-631b59267598.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDAwNDQ4MDAsIm5iZiI6MTc0MDA0NDUwMCwicGF0aCI6Ii84Njg2NDk3LzQxNDY5NTEyMy1hNDg3OGY3Zi00ZDc5LTQwZGEtOWY0Yi02MzFiNTkyNjc1OTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDIyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAyMjBUMDk0MTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTQ0ZDliZDY5OWZmMjc4Y2NjYWI0ZmIzZDMzZWY5NzAzODJjOGU2YWNjZWVmYTE1ZmY2NDhmMzQ3NGY4MTg5ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.PiOytO3haXaZyYVa_7pV5sGQW-xoSv_Jtp1G-mT28qY">
> I'm using v33. It's happening for both legacy theme and the new theming API.

@khoait Interesting... did you find a solution to fix this issue programmatically?

**Comment by BernieSumption** [comment]
@khoait that style node looks like it contains a copy of `ag-grid.css`, but it is not the grid that is injecting it (our style tags all have the `data-ag-global-css` attribute), so I expect some other part of your application's setup is injecting it. I suggest you search your codebase for references to ag-grid.css to find the part of your configuration that is causing this style tag to be injected.

**Comment by khoait** [comment]
@CodrinSocol no solution yet. I'm still investigating. I'll let you know.

@BernieSumption thanks. that's the tricky part as there is only one ag grid component in the react app. I've tried to search for ag-grid.css but it's only in the one using ag grid component. I've also tried the new theming API from v33 without importing ag-grid.css directly but no luck.

the `<style>` node is injected without global attribute like the normal ones. I've tried to comment out the `AgGridReact` in my component, and it doesn't inject the `<style>`. but when I load the `AgGridReact`, the `<style>` is back. So I think it is actually from the Grid.

**Comment by BernieSumption** [comment]
Can you provide more detail on "I've tried to search for ag-grid.css but it's only in the one using ag grid component"? If you're using Theming API, there should be no instances of the string "ag-grid.css" in your application at all.

**Comment by khoait** [comment]
sorry, I meant that I have tried both approaches: `legacy` with ag-grid.css like v32, and the new theming API in v33 without ag-grid.css. Both approaches show the same result with the `<style>` injected.

**Comment by BernieSumption** [comment]
@khoait  OK, so to confirm, when you use Theming API there is no instance of the string "ag-grid.css" across your entire codebase, and the style still gets injected?

At the risk of looking silly if I turn out to be wrong - there's just nothing in our library that injects styles into the head with no attributes. If you're using the UMD bundle and legacy themes, it injects styles with `data-ag-scope="legacy"`. If you're using Theming API it injects with `data-ag-global-css="{css-block-name}"`.

Something in your application is injecting that style. If commenting out `AgGridReact` stops that style from being injected, then the thing injecting only does so if ag grid is on the page.

Try using Chrome DOM Breakpoints to pause execution when an element is added to the DOM, and it should show you the code responsible. Set a JS breakpoint early in your application's initialisation, e.g. by adding `<script>debugger</script>` to the start of your head. Reload your app with dev tools open and it will pause. Add a subtree modification breakpoint on the head element. Resume and it will pause again when any element is added to the head. Keep on resuming until you get to the offending style. Check the stack trace to see where it's coming from. More info on DOM breakpoints: https://developer.chrome.com/docs/devtools/javascript/breakpoints/

**Comment by khoait** [comment]
@BernieSumption thanks for the direction!

> OK, so to confirm, when you use Theming API there is no instance of the string "ag-grid.css" across your entire codebase, and the style still gets injected?

yes, confirmed this is the case. when I used v33 with theming API, I removed all instance of ag-grid.css and theme css.

I'll try to debug using DOM breakpoint as suggested. Really appreciate your prompt responses!

**Comment by khoait** [comment]
@BernieSumption @CodrinSocol I found the issue using DOM breakpoint. And @BernieSumption is right, it is not from the Grid. I'm working with Microsoft PowerApps, they're also using AgGrid for their internal grids. Not sure what they are doing but the `<style>` is loaded from their script. I have to remove it from the DOM before loading my AgGrid.

@BernieSumption thanks for your time and suggestions!

**Comment by rde-sdc** [comment]
@khoait any resolution to this.  I am experiencing the same with powerapps.

**Comment by jklosinski** [comment]
@khoait We are also experiencing the same issue in a powerapps model driven app.  Did MS provide any insight via the support ticket?  And is your workaround to just manually identify the style tag and remove it?

**Comment by khoait** [comment]
@jklosinski @rde-sdc i haven't opened a ticket with MS. I'm using the simple workaround below to remove/add the `<style>` tag. note that if we don't add it back on component destroy, it will break MS grid when we navigate to List View.

in `index.ts`, add this function
```ts
private powerAppsAgGridStyleEls: HTMLStyleElement[];

public disablePowerAppsAgGridStyles(disable: boolean) {
  if (disable) {
    const styleEls = document.head.querySelectorAll("style");

    styleEls.forEach((style) => {
      if (
        style.attributes.length === 0 &&
        style.textContent?.includes("--ag-")
      ) {
        // disable style by removing it from DOM
        style.remove();
        this.powerAppsAgGridStyleEls.push(style);
      }
    });
  } else {
    // enable style by adding it back to DOM
    this.powerAppsAgGridStyleEls.forEach((style) => {
      document.head.appendChild(style);
    });
  }
}
```

call the function in `init` and `destroy`:
```ts
public init(
  context: IExtendedContext,
  notifyOutputChanged: () => void,
  state: ComponentFramework.Dictionary,
  container: HTMLDivElement
): void {
  // redacted...

  this.disablePowerAppsAgGridStyles(true);
}

public destroy(): void {
  // Add code to cleanup control if necessary
  this.disablePowerAppsAgGridStyles(false);
}
```

hope it helps!

**Comment by VicenzoMF** [comment]
I'm still having this bug even after manually deleting the <style>

with <style>:
![Image](https://github.com/user-attachments/assets/cd4b0879-1cb6-44e1-b897-55a57487d920)

without:

![Image](https://github.com/user-attachments/assets/b11ab1f3-2a46-4177-ac95-70b48a19ad2e)

it should be like this(I just pressed f5):

![Image](https://github.com/user-attachments/assets/e59dec1f-3da9-4a6b-a49b-259f2d66cb9f)

Also, I'm getting these squared black box errors.
