### ISSUE TITLE
Error with grandTotalRow and pagination when row count equals paginationPageSize

### ISSUE THREAD

**Issue by NastykSwED** [ag-grid/ag-grid#8368]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Current behavior**

When using `grandTotalRow` with pagination, if the `paginationPageSize` is set to a value and the total number of rows is exactly equal to this value, AG Grid throws the error `Cannot read properties of undefined (reading 'rowIndex')`. This issue occurs for any value of `paginationPageSize`. For example, if `paginationPageSize` is set to 5 and the data has exactly 5 rows, the error still occurs.

**Expected behavior**

The grid should handle the pagination correctly even when the total number of rows is exactly equal to the `paginationPageSize`, and the `grandTotalRow` should be displayed without errors.

**Example**:
https://codesandbox.io/p/sandbox/ag-grid-footer-and-pagination-error-kyws7p

**Please tell us about your environment:**

* **AG Grid version:** 32.0.3

* **Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

* **Language:** React, Typescript

**Comment by AG-Zoheil** [comment]
Hello 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference: **AG-12420**

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can follow the status of this item on the product pipeline page:
https://ag-grid.com/pipeline/

The best way to track this is to sign up for AG Grid new release notifications using [the instructions here](https://ag-grid.zendesk.com/hc/en-us/articles/360002648058-How-do-I-sign-up-for-ag-Grid-release-notifications-). This way you'll know as soon as a new version is out and you can check whether this specific item was implemented on [the changelog page](https://www.ag-grid.com/ag-grid-changelog/).

Thanks again for bringing this up with us.

Kind regards,
Zoheil

**Comment by kimwunhae** [comment]
I am still experiencing this issue in AG Grid v34.

**Scenario:**
- Using `grandTotalRow` (aggFunc total row).
- The grand total row is also being counted in the pagination row count.
- When `paginationPageSize` is set equal to the number of data rows, or when the modulo operation results in 0, the grid throws an exception related to `rowIndex` references (`Cannot read properties of undefined (reading 'rowIndex')`).

**Result:**
- The grid crashes under these conditions.

It seems the issue has not been fully resolved yet. Could you please re‑check this case? @AG-Zoheil
