### ISSUE TITLE
undefined headerRowIndex in "shouldStopEventPropagation"

### ISSUE THREAD

**Issue by lielgut** [ag-grid/ag-grid#8552]
Sorry for not providing a way to reproduce, we got the following error from ag-grid in our logs but were not able to understand what caused it or how to reproduce:
"Cannot read properties of undefined (reading 'headerRowIndex')"
apparently this comes from the following code:
https://github.com/ag-grid/ag-grid/blob/6334ea467a12774343872c23a90cf729048acb3a/community-modules/core/src/headerRendering/cells/abstractCell/abstractHeaderCellCtrl.ts#L99

protected shouldStopEventPropagation(e: KeyboardEvent): boolean {
        const { headerRowIndex, column } = this.focusService.getFocusedHeader()!;
        return _isUserSuppressingHeaderKeyboardEvent(this.gos, e, headerRowIndex, column as AgColumn);
    }

I don't understand the code enough to know why would this.focusService.getFocusedHeader() return undefined headerRowIndex. If someone could explain this issue please that would help a lot.

**Comment by AG-Zoheil** [comment]
Hi

Thank you for submitting this on Github.

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again for the AG Grid community to support.

Kind regards,
Zoheil

**Comment by mikemyl** [comment]
Hey @AG-Zoheil , We are also getting that error:

Unhandled error occurred:  TypeError: Cannot destructure property 'headerRowIndex' of 'this.focusService.getFocusedHeader(...)' as it is null. TypeError: Cannot destructure property 'headerRowIndex' of 'this.focusService.getFocusedHeader(...)' as it is null.
    at classImp.shouldStopEventPropagation <redacted>)
    at HTMLDivElement.keydown (<redacted>)

**Comment by ChristinaMeggs** [comment]
Any update? We have seen this error again

**Comment by hopdxGms** [comment]
> Sorry for not providing a way to reproduce, we got the following error from ag-grid in our logs but were not able to understand what caused it or how to reproduce: "Cannot read properties of undefined (reading 'headerRowIndex')" apparently this comes from the following code:
> 
> [ag-grid/community-modules/core/src/headerRendering/cells/abstractCell/abstractHeaderCellCtrl.ts](https://github.com/ag-grid/ag-grid/blob/6334ea467a12774343872c23a90cf729048acb3a/community-modules/core/src/headerRendering/cells/abstractCell/abstractHeaderCellCtrl.ts#L99)
> 
> Line 99 in [6334ea4](/ag-grid/ag-grid/commit/6334ea467a12774343872c23a90cf729048acb3a)
> 
>  protected shouldStopEventPropagation(e: KeyboardEvent): boolean { 
> protected shouldStopEventPropagation(e: KeyboardEvent): boolean { const { headerRowIndex, column } = this.focusService.getFocusedHeader()!; return _isUserSuppressingHeaderKeyboardEvent(this.gos, e, headerRowIndex, column as AgColumn); }
> 
> I don't understand the code enough to know why would this.focusService.getFocusedHeader() return undefined headerRowIndex. If someone could explain this issue please that would help a lot.

This bug still not fixed. but it is closed??? Do you have other solution?

**Comment by AG-Zoheil** [comment]
Thank you for your comments.

We'd be keen to look into this again. If you are still having problems, can we please ask you to open a new issue with a reproducible live scenario - you can use one of the plunker examples from our [documentation](https://ag-grid.com/javascript-data-grid/) as a starting point.

This would help our team support in the most efficient way, and also increase visibility for the wider AG Grid community in case of contributions and comments.

Much appreciated!

Kind regards,
Zoheil
